Imports System.Data.SqlClient
Imports System.Security.Cryptography
Imports System.Text
Public Class GenerateChart
    Sub GenerateChartMain(ByRef HID As String, ByRef UID As String, ByRef P_List As String(), ByRef H_List As String(), ByRef BirthLagna As String(,), ByRef BirthBhav As String(,), ByRef BirthSouth As String(), ByRef DasaListP As DataTable, ByRef personalDetails As PersonalDetails)
        Dim encryptedHIDUID = Encrypt(HID + UID + DateTime.Now.ToString().Replace("/", "").Replace(" ", "").Replace(":", ""), "sblw-3hn8-sqoy19")
        Dim fPath = "C:\Users\sooraj singh\Documents\" + encryptedHIDUID + ".html"
        'Dim fPath = "C:\inetpub\wwwroot\Templates\" + encryptedHIDUID + ".html"
        Dim afile As New IO.StreamWriter(fPath.Replace("/", "_"), True)
        Dim text = HTMLStringBuilder(HID, UID, P_List, H_List, BirthLagna, BirthBhav, BirthSouth, DasaListP, personalDetails)
        afile.WriteLine(text)
        afile.Close()
        UpdateLink(encryptedHIDUID, HID, UID)
    End Sub
    Function HTMLStringBuilder(ByRef HID As String, ByRef UID As String, ByRef P_List As String(), ByRef H_List As String(), ByRef BirthLagna As String(,), ByRef BirthBhav As String(,), ByRef BirthSouth As String(), ByRef DasaListP As DataTable, ByRef personalDetails As PersonalDetails) As String
        Dim htmlBuilder As StringBuilder = New StringBuilder()
        htmlBuilder.Append(vbCrLf + "<!DOCTYPE html>")
        htmlBuilder.Append(vbCrLf + "<html lang='en'>")
        htmlBuilder.Append(vbCrLf + "")
        htmlBuilder.Append(vbCrLf + "<head>")
        htmlBuilder.Append(vbCrLf + "    <meta charset='UTF-8'>")
        htmlBuilder.Append(vbCrLf + "    <title>Document</title>")
        htmlBuilder.Append(vbCrLf + "</head>")
        htmlBuilder.Append(vbCrLf + "")
        htmlBuilder.Append(vbCrLf + "<body>")
        htmlBuilder.Append(vbCrLf + "")
        htmlBuilder.Append(vbCrLf + "")
        htmlBuilder.Append(vbCrLf + "    <table style='margin: 10px auto 20px;padding: 40px 30px;box-shadow: 0 3px 20px 0px #E1DAD1;border-radius: 8px;'>")
        htmlBuilder.Append(vbCrLf + "        <tr>")
        htmlBuilder.Append(vbCrLf + "            <td>")
        htmlBuilder.Append(vbCrLf + "                <table width='744'>")
        htmlBuilder.Append(vbCrLf + "                    <tr>")
        htmlBuilder.Append(vbCrLf + "                        <td>")
        htmlBuilder.Append(vbCrLf + "                            <p style=' margin: 5px 0;color: #33334B;font-family: sans-serif;font-weight: 600;font-size: 15px;'>Name of the Chart Owner :</p>")
        htmlBuilder.Append(vbCrLf + "                        </td>")
        htmlBuilder.Append(vbCrLf + "                        <td>")
        htmlBuilder.Append(vbCrLf + "                            <p style='margin: 5px 0;color: #33334B;font-family: sans-serif;font-weight: 600;font-size: 14px;'>" + personalDetails.NameoftheChartOwner + "</p>")
        htmlBuilder.Append(vbCrLf + "                        </td>")
        htmlBuilder.Append(vbCrLf + "                    </tr>")
        htmlBuilder.Append(vbCrLf + "                    <tr>")
        htmlBuilder.Append(vbCrLf + "                        <td>")
        htmlBuilder.Append(vbCrLf + "                            <p style=' margin: 5px 0;color: #33334B;font-family: sans-serif;font-weight: 600;font-size: 15px;'>Date of Birth :</p>")
        htmlBuilder.Append(vbCrLf + "                        </td>")
        htmlBuilder.Append(vbCrLf + "                        <td>")
        htmlBuilder.Append(vbCrLf + "                            <p style='margin: 5px 0;color: #33334B;font-family: sans-serif;font-weight: 600;font-size: 14px;'>" + personalDetails.DateofBirth + "</p>")
        htmlBuilder.Append(vbCrLf + "                        </td>")
        htmlBuilder.Append(vbCrLf + "                    </tr>")
        htmlBuilder.Append(vbCrLf + "                    <tr>")
        htmlBuilder.Append(vbCrLf + "                        <td>")
        htmlBuilder.Append(vbCrLf + "                            <p style=' margin: 5px 0;color: #33334B;font-family: sans-serif;font-weight: 600;font-size: 15px;'>Place of Birth :</p>")
        htmlBuilder.Append(vbCrLf + "                        </td>")
        htmlBuilder.Append(vbCrLf + "                        <td>")
        htmlBuilder.Append(vbCrLf + "                            <p style='margin: 5px 0;color: #33334B;font-family: sans-serif;font-weight: 600;font-size: 14px;'>" + personalDetails.PlaceofBirth + "</p>")
        htmlBuilder.Append(vbCrLf + "                        </td>")
        htmlBuilder.Append(vbCrLf + "                    </tr>")
        htmlBuilder.Append(vbCrLf + "                    <tr>")
        htmlBuilder.Append(vbCrLf + "                        <td>")
        htmlBuilder.Append(vbCrLf + "                            <p style=' margin: 5px 0;color: #33334B;font-family: sans-serif;font-weight: 600;font-size: 15px;'>Time of Birth :</p>")
        htmlBuilder.Append(vbCrLf + "                        </td>")
        htmlBuilder.Append(vbCrLf + "                        <td>")
        htmlBuilder.Append(vbCrLf + "                            <p style='margin: 5px 0;color: #33334B;font-family: sans-serif;font-weight: 600;font-size: 14px;'>" + personalDetails.TimeofBirth + "</p>")
        htmlBuilder.Append(vbCrLf + "                        </td>")
        htmlBuilder.Append(vbCrLf + "                    </tr>")
        htmlBuilder.Append(vbCrLf + "                    <tr>")
        htmlBuilder.Append(vbCrLf + "                        <td>")
        htmlBuilder.Append(vbCrLf + "                            <p style=' margin: 5px 0;color: #33334B;font-family: sans-serif;font-weight: 600;font-size: 15px;'>Latitude :</p>")
        htmlBuilder.Append(vbCrLf + "                        </td>")
        htmlBuilder.Append(vbCrLf + "                        <td>")
        htmlBuilder.Append(vbCrLf + "                            <p style='margin: 5px 0;color: #33334B;font-family: sans-serif;font-weight: 600;font-size: 14px;'>" + personalDetails.Latitude + "</p>")
        htmlBuilder.Append(vbCrLf + "                        </td>")
        htmlBuilder.Append(vbCrLf + "                    </tr>")
        htmlBuilder.Append(vbCrLf + "                    <tr>")
        htmlBuilder.Append(vbCrLf + "                        <td>")
        htmlBuilder.Append(vbCrLf + "                            <p style=' margin: 5px 0;color: #33334B;font-family: sans-serif;font-weight: 600;font-size: 15px;'>Longtitude :</p>")
        htmlBuilder.Append(vbCrLf + "                        </td>")
        htmlBuilder.Append(vbCrLf + "                        <td>")
        htmlBuilder.Append(vbCrLf + "                            <p style='margin: 5px 0;color: #33334B;font-family: sans-serif;font-weight: 600;font-size: 14px;'>" + personalDetails.Longitude + "</p>")
        htmlBuilder.Append(vbCrLf + "                        </td>")
        htmlBuilder.Append(vbCrLf + "                    </tr>")
        htmlBuilder.Append(vbCrLf + "                    <tr>")
        htmlBuilder.Append(vbCrLf + "                        <td>")
        htmlBuilder.Append(vbCrLf + "                            <p style=' margin: 5px 0;color: #33334B;font-family: sans-serif;font-weight: 600;font-size: 15px;'>Day of Birth :</p>")
        htmlBuilder.Append(vbCrLf + "                        </td>")
        htmlBuilder.Append(vbCrLf + "                        <td>")
        htmlBuilder.Append(vbCrLf + "                            <p style='margin: 5px 0;color: #33334B;font-family: sans-serif;font-weight: 600;font-size: 14px;'>" + personalDetails.DayofBirth + "</p>")
        htmlBuilder.Append(vbCrLf + "                        </td>")
        htmlBuilder.Append(vbCrLf + "                    </tr>")
        htmlBuilder.Append(vbCrLf + "                    <tr>")
        htmlBuilder.Append(vbCrLf + "                        <td>")
        htmlBuilder.Append(vbCrLf + "                            <p style=' margin: 5px 0;color: #33334B;font-family: sans-serif;font-weight: 600;font-size: 15px;'>Rashi :</p>")
        htmlBuilder.Append(vbCrLf + "                        </td>")
        htmlBuilder.Append(vbCrLf + "                        <td>")
        htmlBuilder.Append(vbCrLf + "                            <p style='margin: 5px 0;color: #33334B;font-family: sans-serif;font-weight: 600;font-size: 14px;'>" + personalDetails.Rashi + "</p>")
        htmlBuilder.Append(vbCrLf + "                        </td>")
        htmlBuilder.Append(vbCrLf + "                    </tr>")
        htmlBuilder.Append(vbCrLf + "                    <tr>")
        htmlBuilder.Append(vbCrLf + "                        <td>")
        htmlBuilder.Append(vbCrLf + "                            <p style=' margin: 5px 0;color: #33334B;font-family: sans-serif;font-weight: 600;font-size: 15px;'>Star :</p>")
        htmlBuilder.Append(vbCrLf + "                        </td>")
        htmlBuilder.Append(vbCrLf + "                        <td>")
        htmlBuilder.Append(vbCrLf + "                            <p style='margin: 5px 0;color: #33334B;font-family: sans-serif;font-weight: 600;font-size: 14px;'>" + personalDetails.Star + "</p>")
        htmlBuilder.Append(vbCrLf + "                        </td>")
        htmlBuilder.Append(vbCrLf + "                    </tr>")
        htmlBuilder.Append(vbCrLf + "                    <tr>")
        htmlBuilder.Append(vbCrLf + "                        <td>")
        htmlBuilder.Append(vbCrLf + "                            <p style=' margin: 5px 0;color: #33334B;font-family: sans-serif;font-weight: 600;font-size: 15px;'>Sun Sign :</p>")
        htmlBuilder.Append(vbCrLf + "                        </td>")
        htmlBuilder.Append(vbCrLf + "                        <td>")
        htmlBuilder.Append(vbCrLf + "                            <p style='margin: 5px 0;color: #33334B;font-family: sans-serif;font-weight: 600;font-size: 14px;'>" + personalDetails.SunSign + "</p>")
        htmlBuilder.Append(vbCrLf + "                        </td>")
        htmlBuilder.Append(vbCrLf + "                    </tr>")
        htmlBuilder.Append(vbCrLf + "                    <tr>")
        htmlBuilder.Append(vbCrLf + "                        <td>")
        htmlBuilder.Append(vbCrLf + "                            <p style=' margin: 5px 0;color: #33334B;font-family: sans-serif;font-weight: 600;font-size: 15px;'>Balance Dasa :</p>")
        htmlBuilder.Append(vbCrLf + "                        </td>")
        htmlBuilder.Append(vbCrLf + "                        <td>")
        htmlBuilder.Append(vbCrLf + "                            <p style='margin: 5px 0;color: #33334B;font-family: sans-serif;font-weight: 600;font-size: 14px;'>" + personalDetails.BalanceDasa + "</p>")
        htmlBuilder.Append(vbCrLf + "                        </td>")
        htmlBuilder.Append(vbCrLf + "                    </tr>")
        htmlBuilder.Append(vbCrLf + "                </table>")
        htmlBuilder.Append(vbCrLf + "            </td>")
        htmlBuilder.Append(vbCrLf + "        </tr>")
        htmlBuilder.Append(vbCrLf + "    </table>")
        htmlBuilder.Append(vbCrLf + "    <table style='margin: 10px auto 20px;padding: 40px 30px;box-shadow: 0 3px 20px 0px #E1DAD1;border-radius: 8px;'>")
        htmlBuilder.Append(vbCrLf + "        <tr>")
        htmlBuilder.Append(vbCrLf + "            <td>")
        htmlBuilder.Append(vbCrLf + "                <h3 class='box-head' style='margin: 0 0 20px;color: #33334B;font-family: sans-serif;font-weight: 600;font-size: 18px;'>Planetary position</h3></td>")
        htmlBuilder.Append(vbCrLf + "        </tr>")
        htmlBuilder.Append(vbCrLf + "        <tr>")
        htmlBuilder.Append(vbCrLf + "            <td>")
        htmlBuilder.Append(vbCrLf + "                <table width='744' style='border: 1px solid #ddd;border-collapse: collapse;padding: 8px;color: #33334B;font-family: sans-serif;font-size: 14px;'>")
        htmlBuilder.Append(vbCrLf + "                    <tr>")
        htmlBuilder.Append(vbCrLf + "                        <th style='border: 1px solid #ddd;border-collapse: collapse;padding: 8px;color: #33334B;font-family: sans-serif;font-size: 14px;'>Planet</th>")
        htmlBuilder.Append(vbCrLf + "                        <th style='border: 1px solid #ddd;border-collapse: collapse;padding: 8px;color: #33334B;font-family: sans-serif;font-size: 14px;'>Sign</th>")
        htmlBuilder.Append(vbCrLf + "                        <th style='border: 1px solid #ddd;border-collapse: collapse;padding: 8px;color: #33334B;font-family: sans-serif;font-size: 14px;'>D-M-S</th>")
        htmlBuilder.Append(vbCrLf + "                        <th style='border: 1px solid #ddd;border-collapse: collapse;padding: 8px;color: #33334B;font-family: sans-serif;font-size: 14px;'>RL</th>")
        htmlBuilder.Append(vbCrLf + "                        <th style='border: 1px solid #ddd;border-collapse: collapse;padding: 8px;color: #33334B;font-family: sans-serif;font-size: 14px;'>STL</th>")
        htmlBuilder.Append(vbCrLf + "                        <th style='border: 1px solid #ddd;border-collapse: collapse;padding: 8px;color: #33334B;font-family: sans-serif;font-size: 14px;'>SL</th>")
        htmlBuilder.Append(vbCrLf + "                        <th style='border: 1px solid #ddd;border-collapse: collapse;padding: 8px;color: #33334B;font-family: sans-serif;font-size: 14px;'>SSL</th>")
        htmlBuilder.Append(vbCrLf + "                        <th style='border: 1px solid #ddd;border-collapse: collapse;padding: 8px;color: #33334B;font-family: sans-serif;font-size: 14px;'>SukL</th>")
        htmlBuilder.Append(vbCrLf + "                        <th style='border: 1px solid #ddd;border-collapse: collapse;padding: 8px;color: #33334B;font-family: sans-serif;font-size: 14px;'>PraL</th>")
        htmlBuilder.Append(vbCrLf + "                        <th style='border: 1px solid #ddd;border-collapse: collapse;padding: 8px;color: #33334B;font-family: sans-serif;font-size: 14px;'>Hse</th>")
        htmlBuilder.Append(vbCrLf + "                        <th style='border: 1px solid #ddd;border-collapse: collapse;padding: 8px;color: #33334B;font-family: sans-serif;font-size: 14px;'>D</th>")
        htmlBuilder.Append(vbCrLf + "                        <th style='border: 1px solid #ddd;border-collapse: collapse;padding: 8px;color: #33334B;font-family: sans-serif;font-size: 14px;'>PS</th>")
        htmlBuilder.Append(vbCrLf + "                    </tr>")
        For i As Integer = 1 To 12
            htmlBuilder.Append(vbCrLf + "                    <tr>")
            htmlBuilder.Append(vbCrLf + "                        <td style='border: 1px solid #ddd;border-collapse: collapse;padding: 8px;color: #33334B;font-family: sans-serif;font-size: 14px;'>" + P_List(i).Split("|")(0) + "</td>")
            htmlBuilder.Append(vbCrLf + "                        <td style='border: 1px solid #ddd;border-collapse: collapse;padding: 8px;color: #33334B;font-family: sans-serif;font-size: 14px;'>" + P_List(i).Split("|")(1) + "</td>")
            htmlBuilder.Append(vbCrLf + "                        <td style='border: 1px solid #ddd;border-collapse: collapse;padding: 8px;color: #33334B;font-family: sans-serif;font-size: 14px;'>" + P_List(i).Split("|")(2) + "</td>")
            htmlBuilder.Append(vbCrLf + "                        <td style='border: 1px solid #ddd;border-collapse: collapse;padding: 8px;color: #33334B;font-family: sans-serif;font-size: 14px;'>" + P_List(i).Split("|")(3) + "</td>")
            htmlBuilder.Append(vbCrLf + "                        <td style='border: 1px solid #ddd;border-collapse: collapse;padding: 8px;color: #33334B;font-family: sans-serif;font-size: 14px;'>" + P_List(i).Split("|")(4) + "</td>")
            htmlBuilder.Append(vbCrLf + "                        <td style='border: 1px solid #ddd;border-collapse: collapse;padding: 8px;color: #33334B;font-family: sans-serif;font-size: 14px;'>" + P_List(i).Split("|")(5) + "</td>")
            htmlBuilder.Append(vbCrLf + "                        <td style='border: 1px solid #ddd;border-collapse: collapse;padding: 8px;color: #33334B;font-family: sans-serif;font-size: 14px;'>" + P_List(i).Split("|")(6) + "</td>")
            htmlBuilder.Append(vbCrLf + "                        <td style='border: 1px solid #ddd;border-collapse: collapse;padding: 8px;color: #33334B;font-family: sans-serif;font-size: 14px;'>" + P_List(i).Split("|")(7) + "</td>")
            htmlBuilder.Append(vbCrLf + "                        <td style='border: 1px solid #ddd;border-collapse: collapse;padding: 8px;color: #33334B;font-family: sans-serif;font-size: 14px;'>" + P_List(i).Split("|")(8) + "</td>")
            htmlBuilder.Append(vbCrLf + "                        <td style='border: 1px solid #ddd;border-collapse: collapse;padding: 8px;color: #33334B;font-family: sans-serif;font-size: 14px;'>" + P_List(i).Split("|")(9) + "</td>")
            htmlBuilder.Append(vbCrLf + "                        <td style='border: 1px solid #ddd;border-collapse: collapse;padding: 8px;color: #33334B;font-family: sans-serif;font-size: 14px;'>" + P_List(i).Split("|")(10) + "</td>")
            htmlBuilder.Append(vbCrLf + "                        <td style='border: 1px solid #ddd;border-collapse: collapse;padding: 8px;color: #33334B;font-family: sans-serif;font-size: 14px;'>" + P_List(i).Split("|")(11) + "</td>")
            htmlBuilder.Append(vbCrLf + "                    </tr>")
        Next

        htmlBuilder.Append(vbCrLf + "                </table>")
        htmlBuilder.Append(vbCrLf + "            </td>")
        htmlBuilder.Append(vbCrLf + "        </tr>")
        htmlBuilder.Append(vbCrLf + "    </table>")
        htmlBuilder.Append(vbCrLf + "    <table style='margin: 10px auto 20px;padding: 40px 30px;box-shadow: 0 3px 20px 0px #E1DAD1;border-radius: 8px;'>")
        htmlBuilder.Append(vbCrLf + "        <tr>")
        htmlBuilder.Append(vbCrLf + "            <td>")
        htmlBuilder.Append(vbCrLf + "                <h3 class='box-head' style='margin: 0 0 20px;color: #33334B;font-family: sans-serif;font-weight: 600;font-size: 18px;'>Cuspal position</h3></td>")
        htmlBuilder.Append(vbCrLf + "        </tr>")
        htmlBuilder.Append(vbCrLf + "        <tr>")
        htmlBuilder.Append(vbCrLf + "            <td>")
        htmlBuilder.Append(vbCrLf + "                <table width='744' style='border: 1px solid #ddd;border-collapse: collapse;padding: 8px;color: #33334B;font-family: sans-serif;font-size: 14px;'>")
        htmlBuilder.Append(vbCrLf + "                    <tr>")
        htmlBuilder.Append(vbCrLf + "                        <th style='border: 1px solid #ddd;border-collapse: collapse;padding: 8px;color: #33334B;font-family: sans-serif;font-size: 14px;'>Cusp</th>")
        htmlBuilder.Append(vbCrLf + "                        <th style='border: 1px solid #ddd;border-collapse: collapse;padding: 8px;color: #33334B;font-family: sans-serif;font-size: 14px;'>Sign</th>")
        htmlBuilder.Append(vbCrLf + "                        <th style='border: 1px solid #ddd;border-collapse: collapse;padding: 8px;color: #33334B;font-family: sans-serif;font-size: 14px;'>D-M-S</th>")
        htmlBuilder.Append(vbCrLf + "                        <th style='border: 1px solid #ddd;border-collapse: collapse;padding: 8px;color: #33334B;font-family: sans-serif;font-size: 14px;'>RL</th>")
        htmlBuilder.Append(vbCrLf + "                        <th style='border: 1px solid #ddd;border-collapse: collapse;padding: 8px;color: #33334B;font-family: sans-serif;font-size: 14px;'>STL</th>")
        htmlBuilder.Append(vbCrLf + "                        <th style='border: 1px solid #ddd;border-collapse: collapse;padding: 8px;color: #33334B;font-family: sans-serif;font-size: 14px;'>SL</th>")
        htmlBuilder.Append(vbCrLf + "                        <th style='border: 1px solid #ddd;border-collapse: collapse;padding: 8px;color: #33334B;font-family: sans-serif;font-size: 14px;'>SSL</th>")
        htmlBuilder.Append(vbCrLf + "                        <th style='border: 1px solid #ddd;border-collapse: collapse;padding: 8px;color: #33334B;font-family: sans-serif;font-size: 14px;'>SukL</th>")
        htmlBuilder.Append(vbCrLf + "                        <th style='border: 1px solid #ddd;border-collapse: collapse;padding: 8px;color: #33334B;font-family: sans-serif;font-size: 14px;'>PraL</th>")
        htmlBuilder.Append(vbCrLf + "                        <th style='border: 1px solid #ddd;border-collapse: collapse;padding: 8px;color: #33334B;font-family: sans-serif;font-size: 14px;'>%SArc</th>")
        htmlBuilder.Append(vbCrLf + "                        <th style='border: 1px solid #ddd;border-collapse: collapse;padding: 8px;color: #33334B;font-family: sans-serif;font-size: 14px;'>%PArc</th>")
        htmlBuilder.Append(vbCrLf + "                    </tr>")
        For i As Integer = 1 To 12
            htmlBuilder.Append(vbCrLf + "                    <tr>")
            htmlBuilder.Append(vbCrLf + "                        <td style='border: 1px solid #ddd;border-collapse: collapse;padding: 8px;color: #33334B;font-family: sans-serif;font-size: 14px;'>" + H_List(i).Split("|")(0) + "</td>")
            htmlBuilder.Append(vbCrLf + "                        <td style='border: 1px solid #ddd;border-collapse: collapse;padding: 8px;color: #33334B;font-family: sans-serif;font-size: 14px;'>" + H_List(i).Split("|")(1) + "</td>")
            htmlBuilder.Append(vbCrLf + "                        <td style='border: 1px solid #ddd;border-collapse: collapse;padding: 8px;color: #33334B;font-family: sans-serif;font-size: 14px;'>" + H_List(i).Split("|")(2) + "</td>")
            htmlBuilder.Append(vbCrLf + "                        <td style='border: 1px solid #ddd;border-collapse: collapse;padding: 8px;color: #33334B;font-family: sans-serif;font-size: 14px;'>" + H_List(i).Split("|")(3) + "</td>")
            htmlBuilder.Append(vbCrLf + "                        <td style='border: 1px solid #ddd;border-collapse: collapse;padding: 8px;color: #33334B;font-family: sans-serif;font-size: 14px;'>" + H_List(i).Split("|")(4) + "</td>")
            htmlBuilder.Append(vbCrLf + "                        <td style='border: 1px solid #ddd;border-collapse: collapse;padding: 8px;color: #33334B;font-family: sans-serif;font-size: 14px;'>" + H_List(i).Split("|")(5) + "</td>")
            htmlBuilder.Append(vbCrLf + "                        <td style='border: 1px solid #ddd;border-collapse: collapse;padding: 8px;color: #33334B;font-family: sans-serif;font-size: 14px;'>" + H_List(i).Split("|")(6) + "</td>")
            htmlBuilder.Append(vbCrLf + "                        <td style='border: 1px solid #ddd;border-collapse: collapse;padding: 8px;color: #33334B;font-family: sans-serif;font-size: 14px;'>" + H_List(i).Split("|")(7) + "</td>")
            htmlBuilder.Append(vbCrLf + "                        <td style='border: 1px solid #ddd;border-collapse: collapse;padding: 8px;color: #33334B;font-family: sans-serif;font-size: 14px;'>" + H_List(i).Split("|")(8) + "</td>")
            htmlBuilder.Append(vbCrLf + "                        <td style='border: 1px solid #ddd;border-collapse: collapse;padding: 8px;color: #33334B;font-family: sans-serif;font-size: 14px;'>" + H_List(i).Split("|")(9) + "</td>")
            htmlBuilder.Append(vbCrLf + "                        <td style='border: 1px solid #ddd;border-collapse: collapse;padding: 8px;color: #33334B;font-family: sans-serif;font-size: 14px;'>" + H_List(i).Split("|")(10) + "</td>")
            htmlBuilder.Append(vbCrLf + "                    </tr>")
        Next
        htmlBuilder.Append(vbCrLf + "                </table>")
        htmlBuilder.Append(vbCrLf + "            </td>")
        htmlBuilder.Append(vbCrLf + "        </tr>")
        htmlBuilder.Append(vbCrLf + "    </table>")
        htmlBuilder.Append(vbCrLf + "    <table style='margin: 10px auto 20px;padding: 40px 30px;box-shadow: 0 3px 20px 0px #E1DAD1;border-radius: 8px;'>")
        htmlBuilder.Append(vbCrLf + "        <tr>")
        htmlBuilder.Append(vbCrLf + "            <td>")
        htmlBuilder.Append(vbCrLf + "                <h3 class='box-head' style='margin: 0 0 20px;color: #33334B;font-family: sans-serif;font-weight: 600;font-size: 18px;'>South Indian chart</h3>")
        htmlBuilder.Append(vbCrLf + "            </td>")
        htmlBuilder.Append(vbCrLf + "        </tr>")
        htmlBuilder.Append(vbCrLf + "        <tr>")
        htmlBuilder.Append(vbCrLf + "            <td>")
        htmlBuilder.Append(vbCrLf + "                <table width='744' style='border: 1px solid #ddd;border-collapse: collapse;padding: 8px;color: #33334B;font-family: sans-serif;font-size: 14px;'>")
        htmlBuilder.Append(vbCrLf + "                    <tr>")
        htmlBuilder.Append(vbCrLf + "                        <td style='width: 25%;height: 100px;text-align: center;border: 1px solid #ff8c00;border-collapse: collapse;padding: 8px;color: #33334B;font-family: sans-serif;font-size: 14px;'>" + BirthSouth(12).Replace(vbCrLf, "<br>").Substring(0, BirthSouth(12).Replace(vbCrLf, "<br>").Length - 4) + "</td>")
        htmlBuilder.Append(vbCrLf + "                        <td style='width: 25%;height: 100px;text-align: center;border: 1px solid #ff8c00;border-collapse: collapse;padding: 8px;color: #33334B;font-family: sans-serif;font-size: 14px;'>" + BirthSouth(1).Replace(vbCrLf, "<br>").Substring(0, BirthSouth(1).Replace(vbCrLf, "<br>").Length - 4) + "</td>")
        htmlBuilder.Append(vbCrLf + "                        <td style='width: 25%;height: 100px;text-align: center;border: 1px solid #ff8c00;border-collapse: collapse;padding: 8px;color: #33334B;font-family: sans-serif;font-size: 14px;'>" + BirthSouth(2).Replace(vbCrLf, "<br>").Substring(0, BirthSouth(2).Replace(vbCrLf, "<br>").Length - 4) + "</td>")
        htmlBuilder.Append(vbCrLf + "                        <td style='width: 25%;height: 100px;text-align: center;border: 1px solid #ff8c00;border-collapse: collapse;padding: 8px;color: #33334B;font-family: sans-serif;font-size: 14px;'>" + BirthSouth(3).Replace(vbCrLf, "<br>").Substring(0, BirthSouth(3).Replace(vbCrLf, "<br>").Length - 4) + "</td>")
        htmlBuilder.Append(vbCrLf + "                    </tr>")
        htmlBuilder.Append(vbCrLf + "                    <tr>")
        htmlBuilder.Append(vbCrLf + "                        <td style='width: 25%;height: 100px;text-align: center;border: 1px solid #ff8c00;border-collapse: collapse;padding: 8px;color: #33334B;font-family: sans-serif;font-size: 14px;'>" + BirthSouth(11).Replace(vbCrLf, "<br>").Substring(0, BirthSouth(11).Replace(vbCrLf, "<br>").Length - 4) + "</td>")
        htmlBuilder.Append(vbCrLf + "                        <td style='width: 25%;height: 100px;text-align: center;border: 1px solid #ff8c00;border-collapse: collapse;padding: 8px;color: #33334B;font-family: sans-serif;font-size: 14px;' rowspan='2' colspan='2'></td>")
        htmlBuilder.Append(vbCrLf + "                        <td style='width: 25%;height: 100px;text-align: center;border: 1px solid #ff8c00;border-collapse: collapse;padding: 8px;color: #33334B;font-family: sans-serif;font-size: 14px;'>" + BirthSouth(4).Replace(vbCrLf, "<br>").Substring(0, BirthSouth(4).Replace(vbCrLf, "<br>").Length - 4) + "</td>")
        htmlBuilder.Append(vbCrLf + "                    </tr>")
        htmlBuilder.Append(vbCrLf + "                    <tr>")
        htmlBuilder.Append(vbCrLf + "                        <td style='width: 25%;height: 100px;text-align: center;border: 1px solid #ff8c00;border-collapse: collapse;padding: 8px;color: #33334B;font-family: sans-serif;font-size: 14px;'>" + BirthSouth(10).Replace(vbCrLf, "<br>").Substring(0, BirthSouth(10).Replace(vbCrLf, "<br>").Length - 4) + "</td>")
        htmlBuilder.Append(vbCrLf + "                        <td style='width: 25%;height: 100px;text-align: center;border: 1px solid #ff8c00;border-collapse: collapse;padding: 8px;color: #33334B;font-family: sans-serif;font-size: 14px;'>" + BirthSouth(5).Replace(vbCrLf, "<br>").Substring(0, BirthSouth(5).Replace(vbCrLf, "<br>").Length - 4) + "</td>")
        htmlBuilder.Append(vbCrLf + "                    </tr>")
        htmlBuilder.Append(vbCrLf + "                    <tr>")
        htmlBuilder.Append(vbCrLf + "                        <td style='width: 25%;height: 100px;text-align: center;border: 1px solid #ff8c00;border-collapse: collapse;padding: 8px;color: #33334B;font-family: sans-serif;font-size: 14px;'>" + BirthSouth(9).Replace(vbCrLf, "<br>").Substring(0, BirthSouth(9).Replace(vbCrLf, "<br>").Length - 4) + "</td>")
        htmlBuilder.Append(vbCrLf + "                        <td style='width: 25%;height: 100px;text-align: center;border: 1px solid #ff8c00;border-collapse: collapse;padding: 8px;color: #33334B;font-family: sans-serif;font-size: 14px;'>" + BirthSouth(8).Replace(vbCrLf, "<br>").Substring(0, BirthSouth(8).Replace(vbCrLf, "<br>").Length - 4) + "</td>")
        htmlBuilder.Append(vbCrLf + "                        <td style='width: 25%;height: 100px;text-align: center;border: 1px solid #ff8c00;border-collapse: collapse;padding: 8px;color: #33334B;font-family: sans-serif;font-size: 14px;'>" + BirthSouth(7).Replace(vbCrLf, "<br>").Substring(0, BirthSouth(7).Replace(vbCrLf, "<br>").Length - 4) + "</td>")
        htmlBuilder.Append(vbCrLf + "                        <td style='width: 25%;height: 100px;text-align: center;border: 1px solid #ff8c00;border-collapse: collapse;padding: 8px;color: #33334B;font-family: sans-serif;font-size: 14px;'>" + BirthSouth(6).Replace(vbCrLf, "<br>").Substring(0, BirthSouth(6).Replace(vbCrLf, "<br>").Length - 4) + "</td>")
        htmlBuilder.Append(vbCrLf + "                    </tr>")
        htmlBuilder.Append(vbCrLf + "                </table>")
        htmlBuilder.Append(vbCrLf + "            </td>")
        htmlBuilder.Append(vbCrLf + "        </tr>")
        htmlBuilder.Append(vbCrLf + "    </table>")
        htmlBuilder.Append(vbCrLf + "    <table style='margin: 10px auto 20px;padding: 40px 30px;box-shadow: 0 3px 20px 0px #E1DAD1;border-radius: 8px;'>")
        htmlBuilder.Append(vbCrLf + "        <tr>")
        htmlBuilder.Append(vbCrLf + "            <td>")
        htmlBuilder.Append(vbCrLf + "                <h3 class='box-head' style='margin: 0 0 20px;color: #33334B;font-family: sans-serif;font-weight: 600;font-size: 18px;'>Dasa listing</h3>")
        htmlBuilder.Append(vbCrLf + "            </td>")
        htmlBuilder.Append(vbCrLf + "        </tr>")
        htmlBuilder.Append(vbCrLf + "        <tr>")
        htmlBuilder.Append(vbCrLf + "            <td>")
        htmlBuilder.Append(vbCrLf + "                <table width='744' style='table-layout:fixed;margin:auto;border: 1px solid #ddd;border-collapse: collapse;padding: 8px;color: #33334B;font-family: sans-serif;font-size: 14px;'>")
        htmlBuilder.Append(vbCrLf + "                    <thead style='display:table;width:calc(744px - 6px);'>")
        htmlBuilder.Append(vbCrLf + "                        <tr>")
        htmlBuilder.Append(vbCrLf + "                            <th style='border-collapse: collapse;padding: 8px;color: #33334B;font-family: sans-serif;font-size: 14px;   border-bottom: 1px solid #ddd;border-right: 1px solid #ddd;width: 93px;'>D</th>")
        htmlBuilder.Append(vbCrLf + "                            <th style='border-collapse: collapse;padding: 8px;color: #33334B;font-family: sans-serif;font-size: 14px;   border-bottom: 1px solid #ddd;border-right: 1px solid #ddd;width: 93px;'>B</th>")
        htmlBuilder.Append(vbCrLf + "                            <th style='border-collapse: collapse;padding: 8px;color: #33334B;font-family: sans-serif;font-size: 14px;   border-bottom: 1px solid #ddd;border-right: 1px solid #ddd;width: 93px;'>A</th>")
        htmlBuilder.Append(vbCrLf + "                            <th style='border-collapse: collapse;padding: 8px;color: #33334B;font-family: sans-serif;font-size: 14px;   border-bottom: 1px solid #ddd;border-right: 1px solid #ddd;width: 93px;'>S</th>")
        htmlBuilder.Append(vbCrLf + "                            <th style='border-collapse: collapse;padding: 8px;color: #33334B;font-family: sans-serif;font-size: 14px;   border-bottom: 1px solid #ddd;border-right: 1px solid #ddd;width: 93px;'>P</th>")
        htmlBuilder.Append(vbCrLf + "                            <th style='border-collapse: collapse;padding: 8px;color: #33334B;font-family: sans-serif;font-size: 14px;   border-bottom: 1px solid #ddd;border-right: 1px solid #ddd;width: 279px;border-right: 0;'>Closing Date & Time</th>")
        htmlBuilder.Append(vbCrLf + "                        </tr>")
        htmlBuilder.Append(vbCrLf + "                    </thead>")
        htmlBuilder.Append(vbCrLf + "                    <tbody style='height:150px;overflow-x:hidden;display:block;width:100%;'>")
        For i As Integer = 0 To DasaListP.Rows.Count - 1
            htmlBuilder.Append(vbCrLf + "                        <tr style='display:table;width:100%;table-layout:fixed;'>")
            htmlBuilder.Append(vbCrLf + "                            <td style='width: 93px;border-collapse: collapse;padding: 8px;color: #33334B;font-family: sans-serif;font-size: 14px;border-right: 1px solid #ddd;'>" + DasaListP.Rows(i).ItemArray(0) + "</td>")
            htmlBuilder.Append(vbCrLf + "                            <td style='width: 93px;border-collapse: collapse;padding: 8px;color: #33334B;font-family: sans-serif;font-size: 14px;border-right: 1px solid #ddd;'>" + DasaListP.Rows(i).ItemArray(1) + "</td>")
            htmlBuilder.Append(vbCrLf + "                            <td style='width: 93px;border-collapse: collapse;padding: 8px;color: #33334B;font-family: sans-serif;font-size: 14px;border-right: 1px solid #ddd;'>" + DasaListP.Rows(i).ItemArray(2) + "</td>")
            htmlBuilder.Append(vbCrLf + "                            <td style='width: 93px;border-collapse: collapse;padding: 8px;color: #33334B;font-family: sans-serif;font-size: 14px;border-right: 1px solid #ddd;'>" + DasaListP.Rows(i).ItemArray(3) + "</td>")
            htmlBuilder.Append(vbCrLf + "                            <td style='width: 279px;border-collapse: collapse;padding: 8px;color: #33334B;font-family: sans-serif;font-size: 14px;border-right: 1px solid #ddd;'>" + DasaListP.Rows(i).ItemArray(4) + "</td>")
            htmlBuilder.Append(vbCrLf + "                            <td style='width: 279px;border-collapse: collapse;padding: 8px;color: #33334B;font-family: sans-serif;font-size: 14px;border-right: 1px solid #ddd;'>" + DasaListP.Rows(i).ItemArray(5) + "</td>")
            htmlBuilder.Append(vbCrLf + "                        </tr>")
        Next
        htmlBuilder.Append(vbCrLf + "                    </tbody>")
        htmlBuilder.Append(vbCrLf + "                </table>")
        htmlBuilder.Append(vbCrLf + "            </td>")
        htmlBuilder.Append(vbCrLf + "        </tr>")
        htmlBuilder.Append(vbCrLf + "    </table>")
        htmlBuilder.Append(vbCrLf + "    <table style='margin: 10px auto 20px;padding: 40px 30px;box-shadow: 0 3px 20px 0px #E1DAD1;border-radius: 8px;'>")
        htmlBuilder.Append(vbCrLf + "        <tr>")
        htmlBuilder.Append(vbCrLf + "            <td>")
        htmlBuilder.Append(vbCrLf + "                <h3 class='original-data' style='margin: 0 0 10px;color: #33334B;font-family: sans-serif;font-weight: 600;font-size: 18px;'>Original data provided by the chart owner</h3>")
        htmlBuilder.Append(vbCrLf + "            </td>")
        htmlBuilder.Append(vbCrLf + "        </tr>")
        htmlBuilder.Append(vbCrLf + "        <tr>")
        htmlBuilder.Append(vbCrLf + "            <td>")
        htmlBuilder.Append(vbCrLf + "                <table width='744' style='margin-bottom: 30px;'>")
        htmlBuilder.Append(vbCrLf + "                    <tr>")
        htmlBuilder.Append(vbCrLf + "                        <td>")
        htmlBuilder.Append(vbCrLf + "                            <p style=' margin: 5px 0;color: #33334B;font-family: sans-serif;font-weight: 600;font-size: 15px;'>Date of Birth :</p>")
        htmlBuilder.Append(vbCrLf + "                        </td>")
        htmlBuilder.Append(vbCrLf + "                        <td>")
        htmlBuilder.Append(vbCrLf + "                            <p style='margin: 5px 0;color: #33334B;font-family: sans-serif;font-weight: 600;font-size: 14px;'>20-08-1993</p>")
        htmlBuilder.Append(vbCrLf + "                        </td>")
        htmlBuilder.Append(vbCrLf + "                    </tr>")
        htmlBuilder.Append(vbCrLf + "                    <tr>")
        htmlBuilder.Append(vbCrLf + "                        <td>")
        htmlBuilder.Append(vbCrLf + "                            <p style=' margin: 5px 0;color: #33334B;font-family: sans-serif;font-weight: 600;font-size: 15px;'>Place of Birth :</p>")
        htmlBuilder.Append(vbCrLf + "                        </td>")
        htmlBuilder.Append(vbCrLf + "                        <td>")
        htmlBuilder.Append(vbCrLf + "                            <p style='margin: 5px 0;color: #33334B;font-family: sans-serif;font-weight: 600;font-size: 14px;'>New Delhi</p>")
        htmlBuilder.Append(vbCrLf + "                        </td>")
        htmlBuilder.Append(vbCrLf + "                    </tr>")
        htmlBuilder.Append(vbCrLf + "                    <tr>")
        htmlBuilder.Append(vbCrLf + "                        <td>")
        htmlBuilder.Append(vbCrLf + "                            <p style=' margin: 5px 0;color: #33334B;font-family: sans-serif;font-weight: 600;font-size: 15px;'>Time of Birth :</p>")
        htmlBuilder.Append(vbCrLf + "                        </td>")
        htmlBuilder.Append(vbCrLf + "                        <td>")
        htmlBuilder.Append(vbCrLf + "                            <p style='margin: 5px 0;color: #33334B;font-family: sans-serif;font-weight: 600;font-size: 14px;'>9:05 AM</p>")
        htmlBuilder.Append(vbCrLf + "                        </td>")
        htmlBuilder.Append(vbCrLf + "                    </tr>")
        htmlBuilder.Append(vbCrLf + "                </table>")
        htmlBuilder.Append(vbCrLf + "            </td>")
        htmlBuilder.Append(vbCrLf + "        </tr>")
        htmlBuilder.Append(vbCrLf + "        <tr>")
        htmlBuilder.Append(vbCrLf + "            <td>")
        htmlBuilder.Append(vbCrLf + "                <h3 class='original-data' style='margin-top: 40px;margin: 0 0 10px;color: #33334B;font-family: sans-serif;font-weight: 600;font-size: 18px;'>Original data provided by the chart owner</h3></td>")
        htmlBuilder.Append(vbCrLf + "        </tr>")
        htmlBuilder.Append(vbCrLf + "        <tr>")
        htmlBuilder.Append(vbCrLf + "            <td>")
        htmlBuilder.Append(vbCrLf + "                <table width='744'>")
        htmlBuilder.Append(vbCrLf + "                    <tr>")
        htmlBuilder.Append(vbCrLf + "                        <td>")
        htmlBuilder.Append(vbCrLf + "                            <p style=' margin: 5px 0;color: #33334B;font-family: sans-serif;font-weight: 600;font-size: 15px;'>Marriage :</p>")
        htmlBuilder.Append(vbCrLf + "                        </td>")
        htmlBuilder.Append(vbCrLf + "                        <td>")
        htmlBuilder.Append(vbCrLf + "                            <p style='margin: 5px 0;color: #33334B;font-family: sans-serif;font-weight: 600;font-size: 14px;'>20-08-1993</p>")
        htmlBuilder.Append(vbCrLf + "                        </td>")
        htmlBuilder.Append(vbCrLf + "                    </tr>")
        htmlBuilder.Append(vbCrLf + "                    <tr>")
        htmlBuilder.Append(vbCrLf + "                        <td>")
        htmlBuilder.Append(vbCrLf + "                            <p style=' margin: 5px 0;color: #33334B;font-family: sans-serif;font-weight: 600;font-size: 15px;'>First child :</p>")
        htmlBuilder.Append(vbCrLf + "                        </td>")
        htmlBuilder.Append(vbCrLf + "                        <td>")
        htmlBuilder.Append(vbCrLf + "                            <p style='margin: 5px 0;color: #33334B;font-family: sans-serif;font-weight: 600;font-size: 14px;'>New Delhi</p>")
        htmlBuilder.Append(vbCrLf + "                        </td>")
        htmlBuilder.Append(vbCrLf + "                    </tr>")
        htmlBuilder.Append(vbCrLf + "                    <tr>")
        htmlBuilder.Append(vbCrLf + "                        <td>")
        htmlBuilder.Append(vbCrLf + "                            <p style=' margin: 5px 0;color: #33334B;font-family: sans-serif;font-weight: 600;font-size: 15px;'>Last call received :</p>")
        htmlBuilder.Append(vbCrLf + "                        </td>")
        htmlBuilder.Append(vbCrLf + "                        <td>")
        htmlBuilder.Append(vbCrLf + "                            <p style='margin: 5px 0;color: #33334B;font-family: sans-serif;font-weight: 600;font-size: 14px;'>9:05 AM</p>")
        htmlBuilder.Append(vbCrLf + "                        </td>")
        htmlBuilder.Append(vbCrLf + "                    </tr>")
        htmlBuilder.Append(vbCrLf + "                    <tr>")
        htmlBuilder.Append(vbCrLf + "                        <td>")
        htmlBuilder.Append(vbCrLf + "                            <p style=' margin: 5px 0;color: #33334B;font-family: sans-serif;font-weight: 600;font-size: 15px;'>Demise of relatives :</p>")
        htmlBuilder.Append(vbCrLf + "                        </td>")
        htmlBuilder.Append(vbCrLf + "                        <td>")
        htmlBuilder.Append(vbCrLf + "                            <p style='margin: 5px 0;color: #33334B;font-family: sans-serif;font-weight: 600;font-size: 14px;'>9:05 AM</p>")
        htmlBuilder.Append(vbCrLf + "                        </td>")
        htmlBuilder.Append(vbCrLf + "                    </tr>")
        htmlBuilder.Append(vbCrLf + "                </table>")
        htmlBuilder.Append(vbCrLf + "            </td>")
        htmlBuilder.Append(vbCrLf + "        </tr>")
        htmlBuilder.Append(vbCrLf + "    </table>")
        htmlBuilder.Append(vbCrLf + "")
        htmlBuilder.Append(vbCrLf + "")
        htmlBuilder.Append(vbCrLf + "    <table style='width:700px;margin: 10px auto 20px;padding: 40px 30px;box-shadow: 0 3px 20px 0px #E1DAD1;border-radius: 8px;box-sizing: border-box;' cellspacing='0' cellpadding='0'>")
        htmlBuilder.Append(vbCrLf + "        <tr>")
        htmlBuilder.Append(vbCrLf + "             <td>")
        htmlBuilder.Append(vbCrLf + "                <h3 style='margin: 0 0 20px;color: #33334B;font-family: sans-serif;font-weight: 600;font-size: 18px;'>North Indian chart</h3>")
        htmlBuilder.Append(vbCrLf + "            </td>")
        htmlBuilder.Append(vbCrLf + "        </tr>")
        htmlBuilder.Append(vbCrLf + "        <tr>")
        htmlBuilder.Append(vbCrLf + "            <td>")
        htmlBuilder.Append(vbCrLf + "                <table  cellspacing='0' cellpadding='0' style='padding: 15px;border: 1px solid #08089a;'>")
        htmlBuilder.Append(vbCrLf + "                    <tbody>")
        htmlBuilder.Append(vbCrLf + "                        <tr>")
        htmlBuilder.Append(vbCrLf + "                            <td>")
        htmlBuilder.Append(vbCrLf + "                                <div style=' position: relative;width: 360px;height: 220px;border: 0px solid #FFF;'>")
        htmlBuilder.Append(vbCrLf + "                                    <div style='position: absolute;width: 15px;height: 15px;border: 1px solid blue;top: -15px;left: -15px;border-top: 0;border-left: 0;'></div>")
        htmlBuilder.Append(vbCrLf + "                                    <div style='position: absolute;height: 15px;width: 2px;background: blue;top: -15px;right: -1px;'></div>")
        htmlBuilder.Append(vbCrLf + "                                    <p style='position: absolute;bottom: 0;right: -5px;'>" + BirthBhav(1, 0) + "</p>")
        htmlBuilder.Append(vbCrLf + "                                    <p style='position: absolute;left: 49%;top: 30%;'>" + BirthBhav(2, 0) + "</p>")
        htmlBuilder.Append(vbCrLf + "                                    <p style='position: absolute;left: 40%;top: 40%;'>" + BirthBhav(3, 0) + "</p>")
        htmlBuilder.Append(vbCrLf + "                                    <div style='position: absolute;top: 50%;left: 10%;transform: translateY(-50%);'>")
        htmlBuilder.Append(vbCrLf + "                                        <p style='margin: 0;font-size: 12px;text-align: center;'>" + BirthBhav(3, 1) + "</p>")
        htmlBuilder.Append(vbCrLf + "                                    </div>")
        htmlBuilder.Append(vbCrLf + "                                    <div style='position: absolute;top: 6%;left: 50%;transform: translateX(-50%);'>")
        htmlBuilder.Append(vbCrLf + "                                        <p style='margin: 0;font-size: 12px;text-align: center;'>" + BirthBhav(2, 1) + "</p>")
        htmlBuilder.Append(vbCrLf + "                                    </div>")
        htmlBuilder.Append(vbCrLf + "                                    <div style='position: absolute;right: -29px;top: 50%;transform: translateY(-50%);'>")
        htmlBuilder.Append(vbCrLf + "                                        <p style='margin: 0;font-size: 12px;text-align: center;'>" + BirthBhav(1, 1) + "</p>")
        htmlBuilder.Append(vbCrLf + "                                    </div>")
        htmlBuilder.Append(vbCrLf + "                                    <svg style='position: absolute;width: 100%;height: 100%;' viewBox='0 0 50 50' preserveAspectRatio='none'>")
        htmlBuilder.Append(vbCrLf + "                                        <line x1='0' y1='0' x2='50' y2='50' stroke='red' stroke-width='0.2'></line>")
        htmlBuilder.Append(vbCrLf + "                                        <line x1='0' y1='50' x2='50' y2='0' stroke='red' stroke-width='0.2'></line>")
        htmlBuilder.Append(vbCrLf + "                                    </svg>")
        htmlBuilder.Append(vbCrLf + "                                </div>")
        htmlBuilder.Append(vbCrLf + "                            </td>")
        htmlBuilder.Append(vbCrLf + "                            <td>")
        htmlBuilder.Append(vbCrLf + "                                <div style='position: relative;width: 360px;height: 220px;border: 0px solid #FFF;'>")
        htmlBuilder.Append(vbCrLf + "                                    <div style='position: absolute;width: 15px;height: 15px;border: 1px solid blue;top: -15px;right: -15px;border-top: 0;border-right: 0;'></div>")
        htmlBuilder.Append(vbCrLf + "                                    <div style='position: absolute;height: 2px;width: 15px;background: blue;bottom: -1px;right: -15px;'></div>")
        htmlBuilder.Append(vbCrLf + "                                    <p style='position: absolute;bottom: -25px;left: 23px;'>" + BirthBhav(10, 0) + "</p>")
        htmlBuilder.Append(vbCrLf + "                                    <p style='position: absolute;right: 49%;top: 30%;'>" + BirthBhav(12, 0) + "</p>")
        htmlBuilder.Append(vbCrLf + "                                    <p style='position: absolute;right: 40%;top: 40%;'>" + BirthBhav(11, 0) + "</p>")
        htmlBuilder.Append(vbCrLf + "                                    <div style='position: absolute;top: 6%;left: 50%;transform: translateX(-50%);'>")
        htmlBuilder.Append(vbCrLf + "                                        <p style='margin: 0;font-size: 12px;text-align: center;'>" + BirthBhav(12, 1) + "</p>")
        htmlBuilder.Append(vbCrLf + "                                    </div>")
        htmlBuilder.Append(vbCrLf + "                                    <div style='position: absolute;top: 50%;right: 9%;transform: translateY(-50%);'>")
        htmlBuilder.Append(vbCrLf + "                                        <p style='margin: 0;font-size: 12px;text-align: center;'>" + BirthBhav(11, 1) + "</p>")
        htmlBuilder.Append(vbCrLf + "                                    </div>")
        htmlBuilder.Append(vbCrLf + "                                    <div style='position: absolute;bottom: -22px;left: 50%;transform: translateX(-50%);'>")
        htmlBuilder.Append(vbCrLf + "                                        <p style='margin: 0;font-size: 12px;text-align: center;'>" + BirthBhav(10, 1) + "</p>")
        htmlBuilder.Append(vbCrLf + "                                    </div>")
        htmlBuilder.Append(vbCrLf + "                                    <svg style='position: absolute;width: 100%;height: 100%;' viewBox='0 0 50 50' preserveAspectRatio='none'>")
        htmlBuilder.Append(vbCrLf + "                                        <line x1='0' y1='0' x2='50' y2='50' stroke='red' stroke-width='0.2'></line>")
        htmlBuilder.Append(vbCrLf + "                                        <line x1='0' y1='50' x2='50' y2='0' stroke='red' stroke-width='0.2'></line>")
        htmlBuilder.Append(vbCrLf + "                                    </svg>")
        htmlBuilder.Append(vbCrLf + "                                </div>")
        htmlBuilder.Append(vbCrLf + "                            </td>")
        htmlBuilder.Append(vbCrLf + "                        </tr>")
        htmlBuilder.Append(vbCrLf + "                        <tr>")
        htmlBuilder.Append(vbCrLf + "                            <td>")
        htmlBuilder.Append(vbCrLf + "                                <div style=' position: relative;width: 360px;height: 220px;border: 0px solid #FFF;'>")
        htmlBuilder.Append(vbCrLf + "                                    <div style='position: absolute;width: 15px;height: 15px;border: 1px solid blue;bottom: -15px;left: -15px;border-bottom: 0;border-left: 0;'></div>")
        htmlBuilder.Append(vbCrLf + "                                    <div style='position: absolute;height: 2px;width: 15px;background: blue;top: -1px;left: -15px;'></div>")
        htmlBuilder.Append(vbCrLf + "                                    <p style='position: absolute;right: 25px;top: -23px;'>" + BirthBhav(4, 0) + "</p>")
        htmlBuilder.Append(vbCrLf + "                                    <p style='position: absolute;left: 40%;top: 40%;'>" + BirthBhav(5, 0) + "</p>")
        htmlBuilder.Append(vbCrLf + "                                    <p style='position: absolute;left: 48%;top: 48.4%;'>" + BirthBhav(6, 0) + "</p>")
        htmlBuilder.Append(vbCrLf + "                                    <div style='position: absolute;top: 50%;left: 10%;transform: translateY(-50%);'>")
        htmlBuilder.Append(vbCrLf + "                                        <p style='margin: 0;font-size: 12px;text-align: center;'>" + BirthBhav(5, 1) + "</p>")
        htmlBuilder.Append(vbCrLf + "                                    </div>")
        htmlBuilder.Append(vbCrLf + "                                    <div style='position: absolute;bottom: 6%;left: 50%;transform: translateX(-50%);'>")
        htmlBuilder.Append(vbCrLf + "                                        <p style='margin: 0;font-size: 12px;text-align: center;'>" + BirthBhav(6, 1) + "</p>")
        htmlBuilder.Append(vbCrLf + "                                    </div>")
        htmlBuilder.Append(vbCrLf + "                                    <div style='position: absolute;top: -13px;left: 50%;transform: translateX(-50%);'>")
        htmlBuilder.Append(vbCrLf + "                                        <p style='margin: 0;font-size: 12px;text-align: center;'>" + BirthBhav(4, 1) + "</p>")
        htmlBuilder.Append(vbCrLf + "                                    </div>")
        htmlBuilder.Append(vbCrLf + "                                    <svg style='position: absolute;width: 100%;height: 100%;' viewBox='0 0 50 50' preserveAspectRatio='none'>")
        htmlBuilder.Append(vbCrLf + "                                        <line x1='0' y1='0' x2='50' y2='50' stroke='red' stroke-width='0.2'></line>")
        htmlBuilder.Append(vbCrLf + "                                        <line x1='0' y1='50' x2='50' y2='0' stroke='red' stroke-width='0.2'></line>")
        htmlBuilder.Append(vbCrLf + "                                    </svg>")
        htmlBuilder.Append(vbCrLf + "                                </div>")
        htmlBuilder.Append(vbCrLf + "                            </td>")
        htmlBuilder.Append(vbCrLf + "                            <td>")
        htmlBuilder.Append(vbCrLf + "                                <div style=' position: relative;width: 360px;height: 220px;border: 0px solid #FFF;'>")
        htmlBuilder.Append(vbCrLf + "                                    <div style='position: absolute;width: 15px;height: 15px;border: 1px solid blue;bottom: -15px;right: -15px;border-bottom: 0;border-right: 0;'></div>")
        htmlBuilder.Append(vbCrLf + "                                    <div style='position: absolute;height: 15px;width: 2px;background: blue;bottom: -15px;left: -1px;'></div>")
        htmlBuilder.Append(vbCrLf + "                                    <p style='position: absolute;left: -4px;top: 0;'>" + BirthBhav(7, 0) + "</p>")
        htmlBuilder.Append(vbCrLf + "                                    <p style='position: absolute;right: 39%;top: 39%;'>" + BirthBhav(8, 0) + "</p>")
        htmlBuilder.Append(vbCrLf + "                                    <p style='position: absolute;right: 48%;top: 48.4%;'>" + BirthBhav(9, 0) + "</p>")
        htmlBuilder.Append(vbCrLf + "                                    <div style='position: absolute;bottom: 6%;left: 50%;transform: translateX(-50%);'>")
        htmlBuilder.Append(vbCrLf + "                                        <p style='margin: 0;font-size: 12px;text-align: center;'>" + BirthBhav(8, 1) + "</p>")
        htmlBuilder.Append(vbCrLf + "                                    </div>")
        htmlBuilder.Append(vbCrLf + "                                    <div style='position: absolute;top: 50%;right: 9%;transform: translateY(-50%);'>")
        htmlBuilder.Append(vbCrLf + "                                        <p style='margin: 0;font-size: 12px;text-align: center;'>" + BirthBhav(9, 1) + "</p>")
        htmlBuilder.Append(vbCrLf + "                                    </div>")
        htmlBuilder.Append(vbCrLf + "                                    <div style='position: absolute;left: -29px;top: 50%;transform: translateY(-50%);'>")
        htmlBuilder.Append(vbCrLf + "                                        <p style='margin: 0;font-size: 12px;text-align: center;'>" + BirthBhav(7, 1) + "</p>")
        htmlBuilder.Append(vbCrLf + "                                    </div>")
        htmlBuilder.Append(vbCrLf + "                                    <svg style='position: absolute;width: 100%;height: 100%;' viewBox='0 0 50 50' preserveAspectRatio='none'>")
        htmlBuilder.Append(vbCrLf + "                                        <line x1='0' y1='0' x2='50' y2='50' stroke='red' stroke-width='0.2'></line>")
        htmlBuilder.Append(vbCrLf + "                                        <line x1='0' y1='50' x2='50' y2='0' stroke='red' stroke-width='0.2'></line>")
        htmlBuilder.Append(vbCrLf + "                                    </svg>")
        htmlBuilder.Append(vbCrLf + "                                </div>")
        htmlBuilder.Append(vbCrLf + "                            </td>")
        htmlBuilder.Append(vbCrLf + "                        </tr>")
        htmlBuilder.Append(vbCrLf + "                    </tbody>")
        htmlBuilder.Append(vbCrLf + "                </table>")
        htmlBuilder.Append(vbCrLf + "            </td>")
        htmlBuilder.Append(vbCrLf + "        </tr>")
        htmlBuilder.Append(vbCrLf + "    </table>")
        htmlBuilder.Append(vbCrLf + "")
        htmlBuilder.Append(vbCrLf + "</body>")
        htmlBuilder.Append(vbCrLf + "")
        htmlBuilder.Append(vbCrLf + "</html>")
        Return htmlBuilder.ToString()
    End Function
    Public Function Encrypt(ByVal input As String, ByVal key As String) As String
        Dim inputArray As Byte() = UTF8Encoding.UTF8.GetBytes(input)
        Dim tripleDES As TripleDESCryptoServiceProvider = New TripleDESCryptoServiceProvider()
        tripleDES.Key = UTF8Encoding.UTF8.GetBytes(key)
        tripleDES.Mode = CipherMode.ECB
        tripleDES.Padding = PaddingMode.PKCS7
        Dim cTransform As ICryptoTransform = tripleDES.CreateEncryptor()
        Dim resultArray As Byte() = cTransform.TransformFinalBlock(inputArray, 0, inputArray.Length)
        tripleDES.Clear()
        Return Convert.ToBase64String(resultArray, 0, resultArray.Length)
    End Function
    Public Function Decrypt(ByVal input As String, ByVal key As String) As String
        Dim inputArray As Byte() = Convert.FromBase64String(input)
        Dim tripleDES As TripleDESCryptoServiceProvider = New TripleDESCryptoServiceProvider()
        tripleDES.Key = UTF8Encoding.UTF8.GetBytes(key)
        tripleDES.Mode = CipherMode.ECB
        tripleDES.Padding = PaddingMode.PKCS7
        Dim cTransform As ICryptoTransform = tripleDES.CreateDecryptor()
        Dim resultArray As Byte() = cTransform.TransformFinalBlock(inputArray, 0, inputArray.Length)
        tripleDES.Clear()
        Return UTF8Encoding.UTF8.GetString(resultArray)
    End Function
    Sub UpdateLink(ByRef linkCode As String, ByRef HID As String, ByRef UID As String)
        Dim con As New SqlConnection
        Dim cmd As New SqlCommand
        Try
            con.ConnectionString = "data source=49.50.103.132;initial catalog=ASTROLOGYSOFTWARE_DB;integrated security=False;User Id=sa;password=pSI)TA1t0K[)"
            con.Open()
            cmd.Connection = con
            cmd.CommandText = $"UPDATE HMAIN
                                    SET HPDF = 'http://49.50.103.132/templates/" + linkCode + ".html' 
                                    WHERE HUSERID = '" + UID + "' AND HID = '" + HID + "'"
            cmd.ExecuteNonQuery()
        Catch ex As Exception
        Finally
            con.Close()
        End Try
    End Sub
End Class