Imports System.Collections.Specialized
Imports System.Data.SqlClient
Imports System.Text

Public Class GenerateChart
    Sub GenerateChartMain(ByRef HID As String, ByRef UID As String, ByRef P_List As String(), ByRef H_List As String(), ByRef BirthLagna As String(,), ByRef BirthBhav As String(,), ByRef BirthSouth As String(), ByRef DasaListP As DataTable, ByRef personalDetails As PersonalDetails)
        Dim fPath = "..\..\HTMLFiles\" + "HID" + "UID" + DateTime.Now.ToString().Replace("/", "").Replace(":", "").Replace("-", "").Replace(" ", "") + ".html"
        Dim afile As New IO.StreamWriter(fPath, True)
        Dim text = HTMLStringBuilder(HID, UID, P_List, H_List, BirthLagna, BirthBhav, BirthSouth, DasaListP, personalDetails)
        afile.WriteLine(text)
        afile.Close()
    End Sub
    Function HTMLStringBuilder(ByRef HID As String, ByRef UID As String, ByRef P_List As String(), ByRef H_List As String(), ByRef BirthLagna As String(,), ByRef BirthBhav As String(,), ByRef BirthSouth As String(), ByRef DasaListP As DataTable, ByRef personalDetails As PersonalDetails) As String
        Dim htmlBuilder As StringBuilder = New StringBuilder()
        htmlBuilder.Append("<!DOCTYPE html>")
        htmlBuilder.Append("<html lang='en'>")
        htmlBuilder.Append("<head>")
        htmlBuilder.Append("	<meta charset='UTF-8'>")
        htmlBuilder.Append("	<title>Document</title>")
        htmlBuilder.Append("</head>")
        htmlBuilder.Append("<style type='text/css'>")
        htmlBuilder.Append("	.box-content {")
        htmlBuilder.Append("	    display: flex;")
        htmlBuilder.Append("	    justify-content: space-between;")
        htmlBuilder.Append("	    align-items: center;")
        htmlBuilder.Append("	}")
        htmlBuilder.Append("	.box-content p:first-child {")
        htmlBuilder.Append("    margin: 10px 0;")
        htmlBuilder.Append("    color: #33334B;")
        htmlBuilder.Append("    font-family: sans-serif;")
        htmlBuilder.Append("    font-weight: 600;")
        htmlBuilder.Append("    font-size: 15px;")
        htmlBuilder.Append("    flex-basis: 35%;")
        htmlBuilder.Append("}")
        htmlBuilder.Append("")
        htmlBuilder.Append("	.box-content p{")
        htmlBuilder.Append("    margin: 10px 0;")
        htmlBuilder.Append("    color: #33334B;")
        htmlBuilder.Append("    font-family: sans-serif;")
        htmlBuilder.Append("    font-weight: 600;")
        htmlBuilder.Append("    font-size: 14px;")
        htmlBuilder.Append("}")
        htmlBuilder.Append("")
        htmlBuilder.Append(".box {")
        htmlBuilder.Append("    width: 50%;")
        htmlBuilder.Append("    margin: 10px auto 20px;")
        htmlBuilder.Append("    padding: 40px 30px;")
        htmlBuilder.Append("    box-shadow: 0 3px 20px 0px #E1DAD1;")
        htmlBuilder.Append("    border-radius: 8px;")
        htmlBuilder.Append("}")
        htmlBuilder.Append("table,tr,td,th{")
        htmlBuilder.Append("	border: 1px solid #ddd;")
        htmlBuilder.Append("	border-collapse: collapse;")
        htmlBuilder.Append("	padding: 8px;")
        htmlBuilder.Append("	color: #33334B;")
        htmlBuilder.Append("	font-family: sans-serif;")
        htmlBuilder.Append("	font-size: 14px;")
        htmlBuilder.Append("}")
        htmlBuilder.Append(".box-head{")
        htmlBuilder.Append("	margin: 0 0 20px;")
        htmlBuilder.Append("    color: #33334B;")
        htmlBuilder.Append("    font-family: sans-serif;")
        htmlBuilder.Append("    font-weight: 600;")
        htmlBuilder.Append("    font-size: 18px;")
        htmlBuilder.Append("}")
        htmlBuilder.Append("table.south-chart tr > td {")
        htmlBuilder.Append("    width: 25%;")
        htmlBuilder.Append("    height: 100px;")
        htmlBuilder.Append("    text-align: center;")
        htmlBuilder.Append("}")
        htmlBuilder.Append("table.south-chart, table.south-chart tr, table.south-chart td{")
        htmlBuilder.Append("	border: 1px solid #ff8c00;")
        htmlBuilder.Append("}")
        htmlBuilder.Append("table.north-chart tr > td {")
        htmlBuilder.Append("    width: 25%;")
        htmlBuilder.Append("    height: 100px;")
        htmlBuilder.Append("    text-align: center;")
        htmlBuilder.Append("}")
        htmlBuilder.Append("table.north-chart, table.north-chart tr, table.north-chart td{")
        htmlBuilder.Append("	border: 1px solid #ff8c00;")
        htmlBuilder.Append("}")
        htmlBuilder.Append(".dasa-list tr,.dasa-list td,.dasa-list th{")
        htmlBuilder.Append("	border: 0;")
        htmlBuilder.Append("}")
        htmlBuilder.Append(".dasa-list th{")
        htmlBuilder.Append("	border: 1px solid #ddd;")
        htmlBuilder.Append("")
        htmlBuilder.Append("}")
        htmlBuilder.Append(".dasa-list tr td{")
        htmlBuilder.Append("	border-right: 1px solid #ddd;")
        htmlBuilder.Append("}")
        htmlBuilder.Append(".original-data{")
        htmlBuilder.Append("    margin: 0 0 20px;")
        htmlBuilder.Append("    color: #33334B;")
        htmlBuilder.Append("    font-family: sans-serif;")
        htmlBuilder.Append("    font-weight: 600;")
        htmlBuilder.Append("    font-size: 18px;")
        htmlBuilder.Append("}")
        htmlBuilder.Append(".dasa-list{                 ")
        htmlBuilder.Append("	table-layout:fixed;     ")
        htmlBuilder.Append("	margin:auto;            ")
        htmlBuilder.Append("}                           ")
        htmlBuilder.Append("                            ")
        htmlBuilder.Append(".dasa-list tbody tr{        ")
        htmlBuilder.Append("    display:table;          ")
        htmlBuilder.Append("	width:100%;             ")
        htmlBuilder.Append("	table-layout:fixed;     ")
        htmlBuilder.Append("  }                         ")
        htmlBuilder.Append("                            ")
        htmlBuilder.Append(".dasa-list tbody{           ")
        htmlBuilder.Append("	height:150px;           ")
        htmlBuilder.Append("	overflow-x:hidden;      ")
        htmlBuilder.Append("	display:block;          ")
        htmlBuilder.Append("	width:100%;             ")
        htmlBuilder.Append("}                           ")
        htmlBuilder.Append(" .dasa-list thead {         ")
        htmlBuilder.Append("	display:table;          ")
        htmlBuilder.Append("	width:calc(100% - 17px);")
        htmlBuilder.Append(" }")
        htmlBuilder.Append("div.s{")
        htmlBuilder.Append("    position: relative;")
        htmlBuilder.Append("    display: inline-block;")
        htmlBuilder.Append("    width: 300px;")
        htmlBuilder.Append("    height: 220px;")
        htmlBuilder.Append("    border: 0px solid #FFF;")
        htmlBuilder.Append("}")
        htmlBuilder.Append("")
        htmlBuilder.Append("svg {")
        htmlBuilder.Append("    position: absolute;")
        htmlBuilder.Append("    width: 100%;")
        htmlBuilder.Append("    height: 100%;")
        htmlBuilder.Append("}")
        htmlBuilder.Append(".first {")
        htmlBuilder.Append("    position: absolute;")
        htmlBuilder.Append("    bottom: 0;")
        htmlBuilder.Append("    right: -5px;")
        htmlBuilder.Append("}")
        htmlBuilder.Append(".second {")
        htmlBuilder.Append("    position: absolute;")
        htmlBuilder.Append("    bottom: -25px;")
        htmlBuilder.Append("    left: 23px;")
        htmlBuilder.Append("}")
        htmlBuilder.Append(".third {")
        htmlBuilder.Append("    position: absolute;")
        htmlBuilder.Append("    right: 25px;")
        htmlBuilder.Append("    top: -23px;")
        htmlBuilder.Append("}")
        htmlBuilder.Append(".forth {")
        htmlBuilder.Append("    position: absolute;")
        htmlBuilder.Append("    left: -4px;")
        htmlBuilder.Append("    top: 0;")
        htmlBuilder.Append("}")
        htmlBuilder.Append(".first-top1 {")
        htmlBuilder.Append("    position: absolute;")
        htmlBuilder.Append("    left: 49%;")
        htmlBuilder.Append("    top: 30%;")
        htmlBuilder.Append("}")
        htmlBuilder.Append(".first-top2 {")
        htmlBuilder.Append("    position: absolute;")
        htmlBuilder.Append("    left: 40%;")
        htmlBuilder.Append("    top: 40%;")
        htmlBuilder.Append("}")
        htmlBuilder.Append(".second-top1{")
        htmlBuilder.Append("    position: absolute;")
        htmlBuilder.Append("    right: 49%;")
        htmlBuilder.Append("    top: 30%;")
        htmlBuilder.Append("}")
        htmlBuilder.Append(".second-top2 {")
        htmlBuilder.Append("    position: absolute;")
        htmlBuilder.Append("    right: 40%;")
        htmlBuilder.Append("    top: 40%;")
        htmlBuilder.Append("}")
        htmlBuilder.Append(".third-top1 {")
        htmlBuilder.Append("    position: absolute;")
        htmlBuilder.Append("    left: 40%;")
        htmlBuilder.Append("    top: 40%;")
        htmlBuilder.Append("}")
        htmlBuilder.Append(".third-top2 {")
        htmlBuilder.Append("    position: absolute;")
        htmlBuilder.Append("    left: 48%;")
        htmlBuilder.Append("    top: 48.4%;")
        htmlBuilder.Append("}")
        htmlBuilder.Append(".forth-top1 {")
        htmlBuilder.Append("    position: absolute;")
        htmlBuilder.Append("    right: 39%;")
        htmlBuilder.Append("    top: 39%;")
        htmlBuilder.Append("}")
        htmlBuilder.Append(".forth-top2 {")
        htmlBuilder.Append("    position: absolute;")
        htmlBuilder.Append("    right: 48%;")
        htmlBuilder.Append("    top: 48.4%;")
        htmlBuilder.Append("}")
        htmlBuilder.Append("")
        htmlBuilder.Append("")
        htmlBuilder.Append(".comman-p p {")
        htmlBuilder.Append("    margin: 0;")
        htmlBuilder.Append("    font-size: 12px;")
        htmlBuilder.Append("    text-align: center;")
        htmlBuilder.Append("}")
        htmlBuilder.Append("")
        htmlBuilder.Append("")
        htmlBuilder.Append(".first-data1 {")
        htmlBuilder.Append("    position: absolute;")
        htmlBuilder.Append("    top: 50%;")
        htmlBuilder.Append("    left: 10%;")
        htmlBuilder.Append("    transform: translateY(-50%);")
        htmlBuilder.Append("}")
        htmlBuilder.Append(".first-data2 {")
        htmlBuilder.Append("    position: absolute;")
        htmlBuilder.Append("    top: 6%;")
        htmlBuilder.Append("    left: 50%;")
        htmlBuilder.Append("    transform: translateX(-50%);")
        htmlBuilder.Append("}")
        htmlBuilder.Append("")
        htmlBuilder.Append("")
        htmlBuilder.Append(".second-data1 {")
        htmlBuilder.Append("    position: absolute;")
        htmlBuilder.Append("    top: 6%;")
        htmlBuilder.Append("    left: 50%;")
        htmlBuilder.Append("    transform: translateX(-50%);")
        htmlBuilder.Append("}")
        htmlBuilder.Append("")
        htmlBuilder.Append(".second-data2 {")
        htmlBuilder.Append("    position: absolute;")
        htmlBuilder.Append("    top: 50%;")
        htmlBuilder.Append("    right: 9%;")
        htmlBuilder.Append("    transform: translateY(-50%);")
        htmlBuilder.Append("}")
        htmlBuilder.Append("")
        htmlBuilder.Append(".third-data1{")
        htmlBuilder.Append("    position: absolute;")
        htmlBuilder.Append("    top: 50%;")
        htmlBuilder.Append("    left: 10%;")
        htmlBuilder.Append("    transform: translateY(-50%);")
        htmlBuilder.Append("}")
        htmlBuilder.Append(".third-data2{")
        htmlBuilder.Append("    position: absolute;")
        htmlBuilder.Append("    bottom: 6%;")
        htmlBuilder.Append("    left: 50%;")
        htmlBuilder.Append("    transform: translateX(-50%);")
        htmlBuilder.Append("}")
        htmlBuilder.Append(".forth-data1{")
        htmlBuilder.Append("    position: absolute;")
        htmlBuilder.Append("    bottom: 6%;")
        htmlBuilder.Append("    left: 50%;")
        htmlBuilder.Append("    transform: translateX(-50%);")
        htmlBuilder.Append("}")
        htmlBuilder.Append(".forth-data2{")
        htmlBuilder.Append("    position: absolute;")
        htmlBuilder.Append("    top: 50%;")
        htmlBuilder.Append("    right: 9%;")
        htmlBuilder.Append("    transform: translateY(-50%);")
        htmlBuilder.Append("}")
        htmlBuilder.Append(".first1-center {")
        htmlBuilder.Append("    position: absolute;")
        htmlBuilder.Append("    right: -29px;")
        htmlBuilder.Append("    top: 50%;")
        htmlBuilder.Append("    transform: translateY(-50%);")
        htmlBuilder.Append("}")
        htmlBuilder.Append(".second1-center{")
        htmlBuilder.Append("    position: absolute;")
        htmlBuilder.Append("    bottom: -22px;")
        htmlBuilder.Append("    left: 50%;")
        htmlBuilder.Append("    transform: translateX(-50%);")
        htmlBuilder.Append("}")
        htmlBuilder.Append(".third1-center{")
        htmlBuilder.Append("    position: absolute;")
        htmlBuilder.Append("    top: -13px;")
        htmlBuilder.Append("    left: 50%;")
        htmlBuilder.Append("    transform: translateX(-50%);")
        htmlBuilder.Append("}")
        htmlBuilder.Append(".forth1-center {")
        htmlBuilder.Append("    position: absolute;")
        htmlBuilder.Append("    left: -29px;")
        htmlBuilder.Append("    top: 50%;")
        htmlBuilder.Append("    transform: translateY(-50%);")
        htmlBuilder.Append("}")
        htmlBuilder.Append(".rectangle{")
        htmlBuilder.Append("    position: absolute;")
        htmlBuilder.Append("    width: 15px;")
        htmlBuilder.Append("    height: 15px;")
        htmlBuilder.Append("    border: 1px solid blue;")
        htmlBuilder.Append("}")
        htmlBuilder.Append(".rectangle1{")
        htmlBuilder.Append("    top: -15px;")
        htmlBuilder.Append("    left: -15px;")
        htmlBuilder.Append("    border-top: 0;")
        htmlBuilder.Append("    border-left: 0;")
        htmlBuilder.Append("}")
        htmlBuilder.Append(".rectangle2{")
        htmlBuilder.Append("    top: -15px;")
        htmlBuilder.Append("    right: -15px;")
        htmlBuilder.Append("    border-top: 0;")
        htmlBuilder.Append("    border-right: 0;")
        htmlBuilder.Append("}")
        htmlBuilder.Append(".rectangle3{")
        htmlBuilder.Append("    bottom: -15px;")
        htmlBuilder.Append("    left: -15px;")
        htmlBuilder.Append("    border-bottom: 0;")
        htmlBuilder.Append("    border-left: 0;")
        htmlBuilder.Append("}")
        htmlBuilder.Append(".rectangle4{")
        htmlBuilder.Append("    bottom: -15px;")
        htmlBuilder.Append("    right: -15px;")
        htmlBuilder.Append("    border-bottom: 0;")
        htmlBuilder.Append("    border-right: 0;")
        htmlBuilder.Append("}")
        htmlBuilder.Append("")
        htmlBuilder.Append(".rectangle1-height{")
        htmlBuilder.Append("  position: absolute;")
        htmlBuilder.Append("  height: 15px;")
        htmlBuilder.Append("  width: 2px;")
        htmlBuilder.Append("  background: blue;")
        htmlBuilder.Append("  top: -15px;")
        htmlBuilder.Append("  right: -1px;")
        htmlBuilder.Append("}")
        htmlBuilder.Append(".rectangle2-height{")
        htmlBuilder.Append("  position: absolute;")
        htmlBuilder.Append("  height:  2px;")
        htmlBuilder.Append("  width: 15px;")
        htmlBuilder.Append("  background: blue;")
        htmlBuilder.Append("  bottom: -1px;")
        htmlBuilder.Append("  right: -15px;")
        htmlBuilder.Append("}")
        htmlBuilder.Append(".rectangle3-height{")
        htmlBuilder.Append("  position: absolute;")
        htmlBuilder.Append("  height:  2px;")
        htmlBuilder.Append("  width: 15px;")
        htmlBuilder.Append("  background: blue;")
        htmlBuilder.Append("  top: -1px;")
        htmlBuilder.Append("  left: -15px;")
        htmlBuilder.Append("}")
        htmlBuilder.Append(".rectangle4-height{")
        htmlBuilder.Append("  position: absolute;")
        htmlBuilder.Append("  height: 15px;")
        htmlBuilder.Append("  width: 2px;")
        htmlBuilder.Append("  background: blue;")
        htmlBuilder.Append("  bottom: -15px;")
        htmlBuilder.Append("  left: -1px;")
        htmlBuilder.Append("}")
        htmlBuilder.Append("</style>")
        htmlBuilder.Append("<body>")
        htmlBuilder.Append("")
        htmlBuilder.Append("	<section>")
        htmlBuilder.Append("		<div class='box'>")
        htmlBuilder.Append("			<div class='box-content'>")
        htmlBuilder.Append("				<p>Name of the Chart Owner :</p>")
        htmlBuilder.Append("				<p>" + personalDetails.NameoftheChartOwner + "</p>")
        htmlBuilder.Append("			</div>")
        htmlBuilder.Append("			<div class='box-content'>")
        htmlBuilder.Append("				<p>Date of Birth :</p>")
        htmlBuilder.Append("				<p>" + personalDetails.DateofBirth + "</p>")
        htmlBuilder.Append("			</div>")
        htmlBuilder.Append("			<div class='box-content'>")
        htmlBuilder.Append("				<p>Place of Birth :</p>")
        htmlBuilder.Append("				<p>" + personalDetails.PlaceofBirth + "</p>")
        htmlBuilder.Append("			</div>")
        htmlBuilder.Append("			<div class='box-content'>")
        htmlBuilder.Append("				<p>Time of Birth :</p>")
        htmlBuilder.Append("				<p>" + personalDetails.TimeofBirth + "</p>")
        htmlBuilder.Append("			</div>")
        htmlBuilder.Append("			<div class='box-content'>")
        htmlBuilder.Append("				<p>Latitude :</p>")
        htmlBuilder.Append("				<p>" + personalDetails.Latitude + "</p>")
        htmlBuilder.Append("			</div>")
        htmlBuilder.Append("			<div class='box-content'>")
        htmlBuilder.Append("				<p>Longtitude :</p>")
        htmlBuilder.Append("				<p>" + personalDetails.Longitude + "</p>")
        htmlBuilder.Append("			</div>")
        htmlBuilder.Append("			<div class='box-content'>")
        htmlBuilder.Append("				<p>Day of Birth :</p>")
        htmlBuilder.Append("				<p>" + personalDetails.DayofBirth + "</p>")
        htmlBuilder.Append("			</div>")
        htmlBuilder.Append("			<div class='box-content'>")
        htmlBuilder.Append("				<p>Rashi :</p>")
        htmlBuilder.Append("				<p>" + personalDetails.Rashi + "</p>")
        htmlBuilder.Append("			</div>")
        htmlBuilder.Append("			<div class='box-content'>")
        htmlBuilder.Append("				<p>Star :</p>")
        htmlBuilder.Append("				<p>" + personalDetails.Star + "</p>")
        htmlBuilder.Append("			</div>")
        htmlBuilder.Append("			<div class='box-content'>")
        htmlBuilder.Append("				<p>Sun Sign :</p>")
        htmlBuilder.Append("				<p>" + personalDetails.SunSign + "</p>")
        htmlBuilder.Append("			</div>")
        htmlBuilder.Append("			<div class='box-content'>")
        htmlBuilder.Append("				<p>Balance Dasa :</p>")
        htmlBuilder.Append("				<p>" + personalDetails.BalanceDasa + "</p>")
        htmlBuilder.Append("			</div>")
        htmlBuilder.Append("		</div>")
        htmlBuilder.Append("	</section>")
        htmlBuilder.Append("")
        htmlBuilder.Append("	<section>")
        htmlBuilder.Append("		<div class='box'>")
        htmlBuilder.Append("			<h3 class='box-head'>Planetary position</h3>")
        htmlBuilder.Append("			<table style='width: 100%;'>")
        htmlBuilder.Append("				<tr>")
        htmlBuilder.Append("				<tr>")
        htmlBuilder.Append("					<th>Planet</th>")
        htmlBuilder.Append("					<th>Sign</th>")
        htmlBuilder.Append("					<th>D-M-S</th>")
        htmlBuilder.Append("					<th>RL</th>")
        htmlBuilder.Append("					<th>STL</th>")
        htmlBuilder.Append("					<th>SL</th>")
        htmlBuilder.Append("					<th>SSL</th>")
        htmlBuilder.Append("					<th>SukL</th>")
        htmlBuilder.Append("					<th>PraL</th>")
        htmlBuilder.Append("					<th>Hse</th>")
        htmlBuilder.Append("					<th>D</th>")
        htmlBuilder.Append("					<th>PS</th>")
        htmlBuilder.Append("				</tr>")
        'GetPlanetaryposition-start
        For i As Integer = 1 To 12
            htmlBuilder.Append("				<tr>")
            htmlBuilder.Append("					<td>" + P_List(i).Split("|")(0) + "</td>")
            htmlBuilder.Append("					<td>" + P_List(i).Split("|")(1) + "</td>")
            htmlBuilder.Append("					<td>" + P_List(i).Split("|")(2) + "</td>")
            htmlBuilder.Append("					<td>" + P_List(i).Split("|")(3) + "</td>")
            htmlBuilder.Append("					<td>" + P_List(i).Split("|")(4) + "</td>")
            htmlBuilder.Append("					<td>" + P_List(i).Split("|")(5) + "</td>")
            htmlBuilder.Append("					<td>" + P_List(i).Split("|")(6) + "</td>")
            htmlBuilder.Append("					<td>" + P_List(i).Split("|")(7) + "</td>")
            htmlBuilder.Append("					<td>" + P_List(i).Split("|")(8) + "</td>")
            htmlBuilder.Append("					<td>" + P_List(i).Split("|")(9) + "</td>")
            htmlBuilder.Append("					<td>" + P_List(i).Split("|")(10) + "</td>")
            htmlBuilder.Append("					<td>" + P_List(i).Split("|")(11) + "</td>")
            htmlBuilder.Append("				</tr>")
        Next
        'GetPlanetaryposition-end
        htmlBuilder.Append("			</table>")
        htmlBuilder.Append("		</div>")
        htmlBuilder.Append("	</section>")
        htmlBuilder.Append("")
        htmlBuilder.Append("	<section>")
        htmlBuilder.Append("		<div class='box'>")
        htmlBuilder.Append("			<h3 class='box-head'>Cuspal position</h3>")
        htmlBuilder.Append("			<table style='width: 100%;'>")
        htmlBuilder.Append("				<tr>")
        htmlBuilder.Append("					<th>Cusp</th>")
        htmlBuilder.Append("					<th>Sign</th>")
        htmlBuilder.Append("					<th>D-M-S</th>")
        htmlBuilder.Append("					<th>RL</th>")
        htmlBuilder.Append("					<th>STL</th>")
        htmlBuilder.Append("					<th>SL</th>")
        htmlBuilder.Append("					<th>SSL</th>")
        htmlBuilder.Append("					<th>SukL</th>")
        htmlBuilder.Append("					<th>PraL</th>")
        htmlBuilder.Append("					<th>%SArc</th>")
        htmlBuilder.Append("					<th>%PArc</th>")
        htmlBuilder.Append("				</tr>")
        'GetCuspalposition-start
        For i As Integer = 1 To 12
            htmlBuilder.Append("				<tr>")
            htmlBuilder.Append("					<td>" + H_List(i).Split("|")(0) + "</td>")
            htmlBuilder.Append("					<td>" + H_List(i).Split("|")(1) + "</td>")
            htmlBuilder.Append("					<td>" + H_List(i).Split("|")(2) + "</td>")
            htmlBuilder.Append("					<td>" + H_List(i).Split("|")(3) + "</td>")
            htmlBuilder.Append("					<td>" + H_List(i).Split("|")(4) + "</td>")
            htmlBuilder.Append("					<td>" + H_List(i).Split("|")(5) + "</td>")
            htmlBuilder.Append("					<td>" + H_List(i).Split("|")(6) + "</td>")
            htmlBuilder.Append("					<td>" + H_List(i).Split("|")(7) + "</td>")
            htmlBuilder.Append("					<td>" + H_List(i).Split("|")(8) + "</td>")
            htmlBuilder.Append("					<td>" + H_List(i).Split("|")(9) + "</td>")
            htmlBuilder.Append("					<td>" + H_List(i).Split("|")(10) + "</td>")
            htmlBuilder.Append("				</tr>")
        Next
        'GetCuspalposition-end
        htmlBuilder.Append("			</table>")
        htmlBuilder.Append("		</div>")
        htmlBuilder.Append("	</section>")
        htmlBuilder.Append("")
        'South Indian chart - start
        htmlBuilder.Append("	<section>")
        htmlBuilder.Append("		<div class='box'>")
        htmlBuilder.Append("			<h3 class='box-head'>South Indian chart</h3>")
        htmlBuilder.Append("			<table style='width: 100%;' class='south-chart'>")
        htmlBuilder.Append("				<tr>")
        htmlBuilder.Append("					<td>" + BirthSouth(12).Replace(vbCrLf, "<br>").Substring(0, BirthSouth(12).Replace(vbCrLf, "<br>").Length - 4) + "</td>")
        htmlBuilder.Append("					<td>" + BirthSouth(1).Replace(vbCrLf, "<br>").Substring(0, BirthSouth(1).Replace(vbCrLf, "<br>").Length - 4) + "</td>")
        htmlBuilder.Append("					<td>" + BirthSouth(2).Replace(vbCrLf, "<br>").Substring(0, BirthSouth(2).Replace(vbCrLf, "<br>").Length - 4) + "</td>")
        htmlBuilder.Append("					<td>" + BirthSouth(3).Replace(vbCrLf, "<br>").Substring(0, BirthSouth(3).Replace(vbCrLf, "<br>").Length - 4) + "</td>")
        htmlBuilder.Append("				</tr>")
        htmlBuilder.Append("				<tr>")
        htmlBuilder.Append("					<td>" + BirthSouth(11).Replace(vbCrLf, "<br>").Substring(0, BirthSouth(11).Replace(vbCrLf, "<br>").Length - 4) + "</td>")
        htmlBuilder.Append("					<td rowspan='2' colspan='2'></td>")
        htmlBuilder.Append("					<td>" + BirthSouth(4).Replace(vbCrLf, "<br>").Substring(0, BirthSouth(4).Replace(vbCrLf, "<br>").Length - 4) + "</td>")
        htmlBuilder.Append("				</tr>")
        htmlBuilder.Append("				<tr>")
        htmlBuilder.Append("					<td>" + BirthSouth(10).Replace(vbCrLf, "<br>").Substring(0, BirthSouth(10).Replace(vbCrLf, "<br>").Length - 4) + "</td>")
        htmlBuilder.Append("					<td>" + BirthSouth(5).Replace(vbCrLf, "<br>").Substring(0, BirthSouth(5).Replace(vbCrLf, "<br>").Length - 4) + "</td>")
        htmlBuilder.Append("				</tr>")
        htmlBuilder.Append("				<tr>")
        htmlBuilder.Append("					<td>" + BirthSouth(9).Replace(vbCrLf, "<br>").Substring(0, BirthSouth(9).Replace(vbCrLf, "<br>").Length - 4) + "</td>")
        htmlBuilder.Append("					<td>" + BirthSouth(8).Replace(vbCrLf, "<br>").Substring(0, BirthSouth(8).Replace(vbCrLf, "<br>").Length - 4) + "</td>")
        htmlBuilder.Append("					<td>" + BirthSouth(7).Replace(vbCrLf, "<br>").Substring(0, BirthSouth(7).Replace(vbCrLf, "<br>").Length - 4) + "</td>")
        htmlBuilder.Append("					<td>" + BirthSouth(6).Replace(vbCrLf, "<br>").Substring(0, BirthSouth(6).Replace(vbCrLf, "<br>").Length - 4) + "</td>")
        htmlBuilder.Append("				</tr>")
        htmlBuilder.Append("			</table>")
        htmlBuilder.Append("		</div>")
        htmlBuilder.Append("	</section>")
        'South Indian chart - ends
        htmlBuilder.Append("")
        'North Indian chart - start
        htmlBuilder.Append("	<section>")
        htmlBuilder.Append("		<div class='box'>")
        htmlBuilder.Append("			<h3 class='box-head'>North Indian chart</h3>")
        htmlBuilder.Append("<table cellspacing='0' cellpadding='0' style='width: 40%;margin: 0 auto;padding: 15px;border: 1px solid #08089a;'>")
        htmlBuilder.Append("    <tbody>")
        htmlBuilder.Append("        <tr>")
        htmlBuilder.Append("            <td>")
        htmlBuilder.Append("                <div class='s'>")
        htmlBuilder.Append("                    <div class='rectangle1 rectangle'></div>")
        htmlBuilder.Append("                    <div class='rectangle1-height'></div>")
        htmlBuilder.Append("                    <p class='first'>3</p>")
        htmlBuilder.Append("                    <p class='first-top1'>4</p>")
        htmlBuilder.Append("                    <p class='first-top2'>5</p>")
        htmlBuilder.Append("                    <div class='first-data1 comman-p'>")
        htmlBuilder.Append("                      <p>20-20-2019</p>")
        htmlBuilder.Append("                      <p>20-20-2019</p>")
        htmlBuilder.Append("                      <p>20-20-2019</p>")
        htmlBuilder.Append("                      <p>20-20-2019</p>")
        htmlBuilder.Append("                    </div>")
        htmlBuilder.Append("                    <div class='first-data2 comman-p'>")
        htmlBuilder.Append("                      <p>20-20-2019</p>")
        htmlBuilder.Append("                      <p>20-20-2019</p>")
        htmlBuilder.Append("                      <p>20-20-2019</p>")
        htmlBuilder.Append("                      <p>20-20-2019</p>")
        htmlBuilder.Append("                    </div>")
        htmlBuilder.Append("                     <div class='first1-center comman-p'>")
        htmlBuilder.Append("                      <p>20-20-2019</p>")
        htmlBuilder.Append("                      <p>20-20-2019</p>")
        htmlBuilder.Append("                    </div>")
        htmlBuilder.Append("                    <svg viewBox='0 0 50 50' preserveAspectRatio='none'>")
        htmlBuilder.Append("                        <line x1='0' y1='0' x2='50' y2='50' stroke='red' stroke-width='0.2'></line>")
        htmlBuilder.Append("                        <line x1='0' y1='50' x2='50' y2='0' stroke='red' stroke-width='0.2'></line>")
        htmlBuilder.Append("                    </svg>")
        htmlBuilder.Append("                </div>")
        htmlBuilder.Append("            </td>")
        htmlBuilder.Append("            <td>")
        htmlBuilder.Append("                <div class='s'>")
        htmlBuilder.Append("                    <div class='rectangle2 rectangle'></div>")
        htmlBuilder.Append("                    <div class='rectangle2-height'></div>")
        htmlBuilder.Append("                    <p class='second'>12</p>")
        htmlBuilder.Append("                    <p class='second-top1'>2</p>")
        htmlBuilder.Append("                    <p class='second-top2'>1</p>")
        htmlBuilder.Append("                    <div class='second-data1 comman-p'>")
        htmlBuilder.Append("                      <p>20-20-2019</p>")
        htmlBuilder.Append("                      <p>20-20-2019</p>")
        htmlBuilder.Append("                      <p>20-20-2019</p>")
        htmlBuilder.Append("                      <p>20-20-2019</p>")
        htmlBuilder.Append("                    </div>")
        htmlBuilder.Append("                    <div class='second-data2 comman-p'>")
        htmlBuilder.Append("                      <p>20-20-2019</p>")
        htmlBuilder.Append("                      <p>20-20-2019</p>")
        htmlBuilder.Append("                      <p>20-20-2019</p>")
        htmlBuilder.Append("                      <p>20-20-2019</p>")
        htmlBuilder.Append("                    </div>")
        htmlBuilder.Append("                    <div class='second1-center comman-p'>")
        htmlBuilder.Append("                      <p>20-20-2019</p>")
        htmlBuilder.Append("                      <p>20-20-2019</p>")
        htmlBuilder.Append("                    </div>")
        htmlBuilder.Append("                    <svg viewBox='0 0 50 50' preserveAspectRatio='none'>")
        htmlBuilder.Append("                        <line x1='0' y1='0' x2='50' y2='50' stroke='red' stroke-width='0.2'></line>")
        htmlBuilder.Append("                        <line x1='0' y1='50' x2='50' y2='0' stroke='red' stroke-width='0.2'></line>")
        htmlBuilder.Append("                    </svg>")
        htmlBuilder.Append("                </div>")
        htmlBuilder.Append("            </td>")
        htmlBuilder.Append("        </tr>")
        htmlBuilder.Append("        <tr>")
        htmlBuilder.Append("            <td>")
        htmlBuilder.Append("                <div class='s'>")
        htmlBuilder.Append("                    <div class='rectangle3 rectangle'></div>")
        htmlBuilder.Append("                    <div class='rectangle3-height'></div>")
        htmlBuilder.Append("                    <p class='third'>6</p>")
        htmlBuilder.Append("                    <p class='third-top1'>7</p>")
        htmlBuilder.Append("                    <p class='third-top2'>8</p>")
        htmlBuilder.Append("                    <div class='third-data1 comman-p'>")
        htmlBuilder.Append("                      <p>20-20-2019</p>")
        htmlBuilder.Append("                      <p>20-20-2019</p>")
        htmlBuilder.Append("                      <p>20-20-2019</p>")
        htmlBuilder.Append("                      <p>20-20-2019</p>")
        htmlBuilder.Append("                    </div>")
        htmlBuilder.Append("                    <div class='third-data2 comman-p'>")
        htmlBuilder.Append("                      <p>20-20-2019</p>")
        htmlBuilder.Append("                      <p>20-20-2019</p>")
        htmlBuilder.Append("                      <p>20-20-2019</p>")
        htmlBuilder.Append("                      <p>20-20-2019</p>")
        htmlBuilder.Append("                    </div>")
        htmlBuilder.Append("                    <div class='third1-center comman-p'>")
        htmlBuilder.Append("                      <p>20-20-2019</p>")
        htmlBuilder.Append("                      <p>20-20-2019</p>")
        htmlBuilder.Append("                    </div>")
        htmlBuilder.Append("                    <svg viewBox='0 0 50 50' preserveAspectRatio='none'>")
        htmlBuilder.Append("                        <line x1='0' y1='0' x2='50' y2='50' stroke='red' stroke-width='0.2'></line>")
        htmlBuilder.Append("                        <line x1='0' y1='50' x2='50' y2='0' stroke='red' stroke-width='0.2'></line>")
        htmlBuilder.Append("                    </svg>")
        htmlBuilder.Append("                </div>")
        htmlBuilder.Append("            </td>")
        htmlBuilder.Append("            <td>")
        htmlBuilder.Append("                <div class='s'>")
        htmlBuilder.Append("                    <div class='rectangle4 rectangle'></div>")
        htmlBuilder.Append("                    <div class='rectangle4-height'></div>")
        htmlBuilder.Append("                    <p class='forth'>9</p>")
        htmlBuilder.Append("                    <p class='forth-top1'>11</p>")
        htmlBuilder.Append("                    <p class='forth-top2'>10</p>")
        htmlBuilder.Append("                     <div class='forth-data1 comman-p'>")
        htmlBuilder.Append("                      <p>20-20-2019</p>")
        htmlBuilder.Append("                      <p>20-20-2019</p>")
        htmlBuilder.Append("                      <p>20-20-2019</p>")
        htmlBuilder.Append("                      <p>20-20-2019</p>")
        htmlBuilder.Append("                    </div>")
        htmlBuilder.Append("                     <div class='forth-data2 comman-p'>")
        htmlBuilder.Append("                      <p>20-20-2019</p>")
        htmlBuilder.Append("                      <p>20-20-2019</p>")
        htmlBuilder.Append("                      <p>20-20-2019</p>")
        htmlBuilder.Append("                      <p>20-20-2019</p>")
        htmlBuilder.Append("                    </div>")
        htmlBuilder.Append("                    <div class='forth1-center comman-p'>")
        htmlBuilder.Append("                      <p>20-20-2019</p>")
        htmlBuilder.Append("                      <p>20-20-2019</p>")
        htmlBuilder.Append("                    </div>")
        htmlBuilder.Append("                    <svg viewBox='0 0 50 50' preserveAspectRatio='none'>")
        htmlBuilder.Append("                        <line x1='0' y1='0' x2='50' y2='50' stroke='red' stroke-width='0.2'></line>")
        htmlBuilder.Append("                        <line x1='0' y1='50' x2='50' y2='0' stroke='red' stroke-width='0.2'></line>")
        htmlBuilder.Append("                    </svg>")
        htmlBuilder.Append("                </div>")
        htmlBuilder.Append("            </td>")
        htmlBuilder.Append("        </tr>")
        htmlBuilder.Append("    </tbody>")
        htmlBuilder.Append("</table>")
        htmlBuilder.Append("		</div>")
        htmlBuilder.Append("	</section>")
        'North Indian chart - ends
        htmlBuilder.Append("")
        htmlBuilder.Append("	<section>")
        htmlBuilder.Append("		<div class='box'>")
        htmlBuilder.Append("			<h3 class='box-head'>Dasha:<br>D : Dasha, B : Bhukti, A : Antara, S : Sookshma, P : Prana</h3>")
        htmlBuilder.Append("			<table class='dasa-list'>")
        htmlBuilder.Append("				<thead>")
        htmlBuilder.Append("				<tr>")
        htmlBuilder.Append("					<th style='width:12.5%'>D</th>")
        htmlBuilder.Append("					<th style='width:12.5%'>B</th>")
        htmlBuilder.Append("					<th style='width:12.5%'>A</th>")
        htmlBuilder.Append("					<th style='width:12.5%'>S</th>")
        htmlBuilder.Append("					<th style='width:12.5%'>P</th>")
        htmlBuilder.Append("					<th style='border-right: 0;width:37.5%;'>Closing Date & Time</th>")
        htmlBuilder.Append("				</tr>")
        htmlBuilder.Append("				</thead>")
        htmlBuilder.Append("				<tbody>")
        'Dasa Lising start
        For i As Integer = 0 To DasaListP.Rows.Count - 1
            htmlBuilder.Append("				<tr>")
            htmlBuilder.Append("					<td>" + DasaListP.Rows(i).ItemArray(0) + "</td>")
            htmlBuilder.Append("					<td>" + DasaListP.Rows(i).ItemArray(1) + "</td>")
            htmlBuilder.Append("					<td>" + DasaListP.Rows(i).ItemArray(2) + "</td>")
            htmlBuilder.Append("					<td>" + DasaListP.Rows(i).ItemArray(3) + "</td>")
            htmlBuilder.Append("					<td>" + DasaListP.Rows(i).ItemArray(4) + "</td>")
            htmlBuilder.Append("					<td>" + DasaListP.Rows(i).ItemArray(5) + "</td>")
            htmlBuilder.Append("				</tr>")
        Next
        htmlBuilder.Append("				<tr>")
        htmlBuilder.Append("					<td>THe Moon</td>")
        htmlBuilder.Append("					<td>THe Moon</td>")
        htmlBuilder.Append("					<td>THe Moon</td>")
        htmlBuilder.Append("					<td>THe Moon</td>")
        htmlBuilder.Append("					<td>1</td>")
        htmlBuilder.Append("					<td>upto 1 year</td>")
        htmlBuilder.Append("				</tr>")
        'Dasa Lsting ends
        htmlBuilder.Append("				</tbody>")
        htmlBuilder.Append("			</table>")
        htmlBuilder.Append("		</div>")
        htmlBuilder.Append("	</section>")
        htmlBuilder.Append("")
        htmlBuilder.Append("	<section>")
        htmlBuilder.Append("		<div class='box'>")
        htmlBuilder.Append("			<h3 class='original-data'>Original data provided by the chart owner</h3>")
        htmlBuilder.Append("			<div class='box-content'>")
        htmlBuilder.Append("				<p>Date of Birth :</p>")
        htmlBuilder.Append("				<p>20-08-1993</p>")
        htmlBuilder.Append("			</div>")
        htmlBuilder.Append("			<div class='box-content'>")
        htmlBuilder.Append("				<p>Place of Birth :</p>")
        htmlBuilder.Append("				<p>New Delhi</p>")
        htmlBuilder.Append("			</div>")
        htmlBuilder.Append("			<div class='box-content'>")
        htmlBuilder.Append("				<p>Time of Birth :</p>")
        htmlBuilder.Append("				<p>9:05 AM</p>")
        htmlBuilder.Append("			</div>")
        htmlBuilder.Append("			<h3 class='original-data' style='margin-top: 40px;'>Original data provided by the chart owner</h3>")
        htmlBuilder.Append("			<div class='box-content'>")
        htmlBuilder.Append("				<p>Marriage :</p>")
        htmlBuilder.Append("				<p>20-08-1993</p>")
        htmlBuilder.Append("			</div>")
        htmlBuilder.Append("			<div class='box-content'>")
        htmlBuilder.Append("				<p>First child :</p>")
        htmlBuilder.Append("				<p>New Delhi</p>")
        htmlBuilder.Append("			</div>")
        htmlBuilder.Append("			<div class='box-content'>")
        htmlBuilder.Append("				<p>Last call received :</p>")
        htmlBuilder.Append("				<p>9:05 AM</p>")
        htmlBuilder.Append("			</div>")
        htmlBuilder.Append("			<div class='box-content'>")
        htmlBuilder.Append("				<p>Demise of relatives :</p>")
        htmlBuilder.Append("				<p>9:05 AM</p>")
        htmlBuilder.Append("			</div>")
        htmlBuilder.Append("		</div>")
        htmlBuilder.Append("	</section>")
        htmlBuilder.Append("</body>")
        htmlBuilder.Append("</html>")
        Return htmlBuilder.ToString()
    End Function
End Class
