Imports System.Data.SqlClient
Imports System.Text

Public Class GenerateChart
    Sub GenerateChartMain(ByRef HID As String, ByRef UID As String)
        GetUserNameFromUPROF(UID)

        Dim fPath = "..\..\HTMLFiles\" + "HID" + "UID" + DateTime.Now.ToString().Replace("/", "").Replace(":", "").Replace("-", "").Replace(" ", "") + ".html"
        Dim afile As New IO.StreamWriter(fPath, True)
        Dim text = HTMLStringBuilder("HID", "UID")
        afile.WriteLine(text)
        afile.Close()
    End Sub
    Function HTMLStringBuilder(ByRef HID As String, ByRef UID As String) As String
        Dim htmlBuilder As StringBuilder = New StringBuilder()
        htmlBuilder.Append("<!DOCTYPE html>")
        htmlBuilder.Append("<html lang='en'>")
        htmlBuilder.Append("<head>")
        htmlBuilder.Append("	<meta charset='UTF-8'>")
        htmlBuilder.Append("	<title>Document</title>")
        htmlBuilder.Append("</head>")
        htmlBuilder.Append("<style type='text/css'>")
        htmlBuilder.Append("	.box-content {")
        htmlBuilder.Append("	    display: flex;")
        htmlBuilder.Append("	    justify-content: space-between;")
        htmlBuilder.Append("	    align-items: center;")
        htmlBuilder.Append("	}")
        htmlBuilder.Append("	.box-content p:first-child {")
        htmlBuilder.Append("    margin: 10px 0;")
        htmlBuilder.Append("    color: #33334B;")
        htmlBuilder.Append("    font-family: sans-serif;")
        htmlBuilder.Append("    font-weight: 600;")
        htmlBuilder.Append("    font-size: 15px;")
        htmlBuilder.Append("    flex-basis: 35%;")
        htmlBuilder.Append("}")
        htmlBuilder.Append("")
        htmlBuilder.Append("	.box-content p{")
        htmlBuilder.Append("    margin: 10px 0;")
        htmlBuilder.Append("    color: #33334B;")
        htmlBuilder.Append("    font-family: sans-serif;")
        htmlBuilder.Append("    font-weight: 600;")
        htmlBuilder.Append("    font-size: 14px;")
        htmlBuilder.Append("}")
        htmlBuilder.Append("")
        htmlBuilder.Append(".box {")
        htmlBuilder.Append("    width: 50%;")
        htmlBuilder.Append("    margin: 10px auto 20px;")
        htmlBuilder.Append("    padding: 40px 30px;")
        htmlBuilder.Append("    box-shadow: 0 3px 20px 0px #E1DAD1;")
        htmlBuilder.Append("    border-radius: 8px;")
        htmlBuilder.Append("}")
        htmlBuilder.Append("table,tr,td,th{")
        htmlBuilder.Append("	border: 1px solid #ddd;")
        htmlBuilder.Append("	border-collapse: collapse;")
        htmlBuilder.Append("	padding: 8px;")
        htmlBuilder.Append("	color: #33334B;")
        htmlBuilder.Append("	font-family: sans-serif;")
        htmlBuilder.Append("	font-size: 14px;")
        htmlBuilder.Append("}")
        htmlBuilder.Append(".box-head{")
        htmlBuilder.Append("	margin: 0 0 20px;")
        htmlBuilder.Append("    color: #33334B;")
        htmlBuilder.Append("    font-family: sans-serif;")
        htmlBuilder.Append("    font-weight: 600;")
        htmlBuilder.Append("    font-size: 18px;")
        htmlBuilder.Append("}")
        htmlBuilder.Append("table.south-chart tr > td {")
        htmlBuilder.Append("    width: 25%;")
        htmlBuilder.Append("    height: 100px;")
        htmlBuilder.Append("    text-align: center;")
        htmlBuilder.Append("}")
        htmlBuilder.Append("table.south-chart, table.south-chart tr, table.south-chart td{")
        htmlBuilder.Append("	border: 1px solid #ff8c00;")
        htmlBuilder.Append("}")
        htmlBuilder.Append("table.north-chart tr > td {")
        htmlBuilder.Append("    width: 25%;")
        htmlBuilder.Append("    height: 100px;")
        htmlBuilder.Append("    text-align: center;")
        htmlBuilder.Append("}")
        htmlBuilder.Append("table.north-chart, table.north-chart tr, table.north-chart td{")
        htmlBuilder.Append("	border: 1px solid #ff8c00;")
        htmlBuilder.Append("}")
        htmlBuilder.Append(".dasa-list tr,.dasa-list td,.dasa-list th{")
        htmlBuilder.Append("	border: 0;")
        htmlBuilder.Append("}")
        htmlBuilder.Append(".dasa-list th{")
        htmlBuilder.Append("	border: 1px solid #ddd;")
        htmlBuilder.Append("")
        htmlBuilder.Append("}")
        htmlBuilder.Append(".dasa-list tr td{")
        htmlBuilder.Append("	border-right: 1px solid #ddd;")
        htmlBuilder.Append("}")
        htmlBuilder.Append(".original-data{")
        htmlBuilder.Append("    margin: 0 0 20px;")
        htmlBuilder.Append("    color: #33334B;")
        htmlBuilder.Append("    font-family: sans-serif;")
        htmlBuilder.Append("    font-weight: 600;")
        htmlBuilder.Append("    font-size: 18px;")
        htmlBuilder.Append("}")
        htmlBuilder.Append("</style>")
        htmlBuilder.Append("<body>")
        htmlBuilder.Append("")
        htmlBuilder.Append("	<section>")
        htmlBuilder.Append("		<div class='box'>")
        htmlBuilder.Append("			<div class='box-content'>")
        htmlBuilder.Append("				<p>Name of the Chart Owner :</p>")
        htmlBuilder.Append("				<p>" + NameoftheChartOwner + "</p>")
        htmlBuilder.Append("			</div>")
        htmlBuilder.Append("			<div class='box-content'>")
        htmlBuilder.Append("				<p>Date of Birth :</p>")
        htmlBuilder.Append("				<p>" + DateofBirth + "</p>")
        htmlBuilder.Append("			</div>")
        htmlBuilder.Append("			<div class='box-content'>")
        htmlBuilder.Append("				<p>Place of Birth :</p>")
        htmlBuilder.Append("				<p>" + PlaceofBirth + "</p>")
        htmlBuilder.Append("			</div>")
        htmlBuilder.Append("			<div class='box-content'>")
        htmlBuilder.Append("				<p>Time of Birth :</p>")
        htmlBuilder.Append("				<p>" + TimeofBirth + "</p>")
        htmlBuilder.Append("			</div>")
        htmlBuilder.Append("			<div class='box-content'>")
        htmlBuilder.Append("				<p>Latitude :</p>")
        htmlBuilder.Append("				<p>" + Latitude + "</p>")
        htmlBuilder.Append("			</div>")
        htmlBuilder.Append("			<div class='box-content'>")
        htmlBuilder.Append("				<p>Longtitude :</p>")
        htmlBuilder.Append("				<p>" + Longitude + "</p>")
        htmlBuilder.Append("			</div>")
        htmlBuilder.Append("			<div class='box-content'>")
        htmlBuilder.Append("				<p>Day of Birth :</p>")
        htmlBuilder.Append("				<p>" + DayofBirth + "</p>")
        htmlBuilder.Append("			</div>")
        htmlBuilder.Append("			<div class='box-content'>")
        htmlBuilder.Append("				<p>Rashi :</p>")
        htmlBuilder.Append("				<p>" + Rashi + "</p>")
        htmlBuilder.Append("			</div>")
        htmlBuilder.Append("			<div class='box-content'>")
        htmlBuilder.Append("				<p>Star :</p>")
        htmlBuilder.Append("				<p>" + Star + "</p>")
        htmlBuilder.Append("			</div>")
        htmlBuilder.Append("			<div class='box-content'>")
        htmlBuilder.Append("				<p>Sun Sign :</p>")
        htmlBuilder.Append("				<p>" + SunSign + "</p>")
        htmlBuilder.Append("			</div>")
        htmlBuilder.Append("			<div class='box-content'>")
        htmlBuilder.Append("				<p>Balance Dasa :</p>")
        htmlBuilder.Append("				<p>" + BalanceDasa + "</p>")
        htmlBuilder.Append("			</div>")
        htmlBuilder.Append("		</div>")
        htmlBuilder.Append("	</section>")
        htmlBuilder.Append("")
        htmlBuilder.Append("	<section>")
        htmlBuilder.Append("		<div class='box'>")
        htmlBuilder.Append("			<h3 class='box-head'>Planetary position</h3>")
        htmlBuilder.Append("			<table style='width: 100%;'>")
        htmlBuilder.Append("				<tr>")
        htmlBuilder.Append("					<th>Planet</th>")
        htmlBuilder.Append("					<th>Sign</th>")
        htmlBuilder.Append("					<th>D-M-S</th>")
        htmlBuilder.Append("					<th>RL</th>")
        htmlBuilder.Append("					<th>STL</th>")
        htmlBuilder.Append("					<th>SL</th>")
        htmlBuilder.Append("					<th>SSL</th>")
        htmlBuilder.Append("					<th>SukL</th>")
        htmlBuilder.Append("					<th>PraL</th>")
        htmlBuilder.Append("					<th>Hse</th>")
        htmlBuilder.Append("					<th>D</th>")
        htmlBuilder.Append("					<th>PS</th>")
        htmlBuilder.Append("				</tr>")
        'GetPlanetaryposition-start
        htmlBuilder.Append("				<tr>")
        htmlBuilder.Append("					<td>Sun</td>")
        htmlBuilder.Append("					<td>Leo</td>")
        htmlBuilder.Append("					<td>11-33-20</td>")
        htmlBuilder.Append("					<td>A</td>")
        htmlBuilder.Append("					<td>B</td>")
        htmlBuilder.Append("					<td>C</td>")
        htmlBuilder.Append("					<td>D</td>")
        htmlBuilder.Append("					<td>E</td>")
        htmlBuilder.Append("					<td>F</td>")
        htmlBuilder.Append("					<td>G</td>")
        htmlBuilder.Append("					<td>H</td>")
        htmlBuilder.Append("					<td>I</td>")
        htmlBuilder.Append("				</tr>")
        'GetPlanetaryposition-end
        htmlBuilder.Append("			</table>")
        htmlBuilder.Append("		</div>")
        htmlBuilder.Append("	</section>")
        htmlBuilder.Append("")
        htmlBuilder.Append("	<section>")
        htmlBuilder.Append("		<div class='box'>")
        htmlBuilder.Append("			<h3 class='box-head'>Cuspal position</h3>")
        htmlBuilder.Append("			<table style='width: 100%;'>")
        htmlBuilder.Append("				<tr>")
        htmlBuilder.Append("					<th>Cusp</th>")
        htmlBuilder.Append("					<th>Sign</th>")
        htmlBuilder.Append("					<th>D-M-S</th>")
        htmlBuilder.Append("					<th>RL</th>")
        htmlBuilder.Append("					<th>STL</th>")
        htmlBuilder.Append("					<th>SL</th>")
        htmlBuilder.Append("					<th>SSL</th>")
        htmlBuilder.Append("					<th>SukL</th>")
        htmlBuilder.Append("					<th>PraL</th>")
        htmlBuilder.Append("					<th>%SArc</th>")
        htmlBuilder.Append("					<th>%PArc</th>")
        htmlBuilder.Append("				</tr>")
        'GetCuspalposition-start
        htmlBuilder.Append("				<tr>")
        htmlBuilder.Append("					<td>Sun</td>")
        htmlBuilder.Append("					<td>Leo</td>")
        htmlBuilder.Append("					<td>11-33-20</td>")
        htmlBuilder.Append("					<td>A</td>")
        htmlBuilder.Append("					<td>B</td>")
        htmlBuilder.Append("					<td>C</td>")
        htmlBuilder.Append("					<td>D</td>")
        htmlBuilder.Append("					<td>E</td>")
        htmlBuilder.Append("					<td>F</td>")
        htmlBuilder.Append("					<td>G</td>")
        htmlBuilder.Append("					<td>H</td>")
        htmlBuilder.Append("				</tr>")
        'GetCuspalposition-end
        htmlBuilder.Append("			</table>")
        htmlBuilder.Append("		</div>")
        htmlBuilder.Append("	</section>")
        htmlBuilder.Append("")
        'South Indian chart - start
        htmlBuilder.Append("	<section>")
        htmlBuilder.Append("		<div class='box'>")
        htmlBuilder.Append("			<h3 class='box-head'>South Indian chart</h3>")
        htmlBuilder.Append("			<table style='width: 100%;' class='south-chart'>")
        htmlBuilder.Append("				<tr>")
        htmlBuilder.Append("					<td>" + SI_12 + "</td>")
        htmlBuilder.Append("					<td>" + SI_01 + "</td>")
        htmlBuilder.Append("					<td>" + SI_02 + "</td>")
        htmlBuilder.Append("					<td>" + SI_03 + "</td>")
        htmlBuilder.Append("				</tr>")
        htmlBuilder.Append("				<tr>")
        htmlBuilder.Append("					<td>" + SI_11 + "</td>")
        htmlBuilder.Append("					<td rowspan='2' colspan='2'>" + Center + "</td>")
        htmlBuilder.Append("					<td>" + SI_04 + "</td>")
        htmlBuilder.Append("				</tr>")
        htmlBuilder.Append("				<tr>")
        htmlBuilder.Append("					<td>" + SI_10 + "</td>")
        htmlBuilder.Append("					<td>" + SI_05 + "</td>")
        htmlBuilder.Append("				</tr>")
        htmlBuilder.Append("				<tr>")
        htmlBuilder.Append("					<td>" + SI_09 + "</td>")
        htmlBuilder.Append("					<td>" + SI_08 + "</td>")
        htmlBuilder.Append("					<td>" + SI_07 + "</td>")
        htmlBuilder.Append("					<td>" + SI_06 + "</td>")
        htmlBuilder.Append("				</tr>")
        htmlBuilder.Append("			</table>")
        htmlBuilder.Append("		</div>")
        htmlBuilder.Append("	</section>")
        'South Indian chart - ends
        htmlBuilder.Append("")
        'North Indian chart - start
        htmlBuilder.Append("	<section>")
        htmlBuilder.Append("		<div class='box'>")
        htmlBuilder.Append("			<h3 class='box-head'>North Indian chart</h3>")
        htmlBuilder.Append("			<table style='width: 100%;' class='north-chart'>")
        htmlBuilder.Append("				<tr>")
        htmlBuilder.Append("					<td></td>")
        htmlBuilder.Append("				</tr>")
        htmlBuilder.Append("			</table>")
        htmlBuilder.Append("		</div>")
        htmlBuilder.Append("	</section>")
        htmlBuilder.Append("")
        htmlBuilder.Append("	<section>")
        htmlBuilder.Append("		<div class='box'>")
        htmlBuilder.Append("			<h3 class='box-head'>Dasa listing</h3>")
        htmlBuilder.Append("			<table style='width: 100%;' class='dasa-list'>")
        htmlBuilder.Append("				<tr>")
        htmlBuilder.Append("					<th>Planet ruling Natural dasa</th>")
        htmlBuilder.Append("					<th>No of years</th>")
        htmlBuilder.Append("					<th>Age group</th>")
        htmlBuilder.Append("				</tr>")
        htmlBuilder.Append("				<tr>")
        htmlBuilder.Append("					<td>THe Moon</td>")
        htmlBuilder.Append("					<td>1</td>")
        htmlBuilder.Append("					<td>upto 1 year</td>")
        htmlBuilder.Append("				</tr>")
        htmlBuilder.Append("				<tr>")
        htmlBuilder.Append("					<td>Mars</td>")
        htmlBuilder.Append("					<td>2</td>")
        htmlBuilder.Append("					<td>upto 2 year</td>")
        htmlBuilder.Append("				</tr>")
        htmlBuilder.Append("			</table>")
        htmlBuilder.Append("		</div>")
        htmlBuilder.Append("	</section>")
        'North Indian chart - ends
        htmlBuilder.Append("")
        htmlBuilder.Append("	<section>")
        htmlBuilder.Append("		<div class='box'>")
        htmlBuilder.Append("			<h3 class='original-data'>Original data provided by the chart owner</h3>")
        htmlBuilder.Append("			<div class='box-content'>")
        htmlBuilder.Append("				<p>Date of Birth :</p>")
        htmlBuilder.Append("				<p>20-08-1993</p>")
        htmlBuilder.Append("			</div>")
        htmlBuilder.Append("			<div class='box-content'>")
        htmlBuilder.Append("				<p>Place of Birth :</p>")
        htmlBuilder.Append("				<p>New Delhi</p>")
        htmlBuilder.Append("			</div>")
        htmlBuilder.Append("			<div class='box-content'>")
        htmlBuilder.Append("				<p>Time of Birth :</p>")
        htmlBuilder.Append("				<p>9:05 AM</p>")
        htmlBuilder.Append("			</div>")
        htmlBuilder.Append("			<h3 class='original-data' style='margin-top: 40px;'>Original data provided by the chart owner</h3>")
        htmlBuilder.Append("			<div class='box-content'>")
        htmlBuilder.Append("				<p>Marriage :</p>")
        htmlBuilder.Append("				<p>20-08-1993</p>")
        htmlBuilder.Append("			</div>")
        htmlBuilder.Append("			<div class='box-content'>")
        htmlBuilder.Append("				<p>First child :</p>")
        htmlBuilder.Append("				<p>New Delhi</p>")
        htmlBuilder.Append("			</div>")
        htmlBuilder.Append("			<div class='box-content'>")
        htmlBuilder.Append("				<p>Last call received :</p>")
        htmlBuilder.Append("				<p>9:05 AM</p>")
        htmlBuilder.Append("			</div>")
        htmlBuilder.Append("			<div class='box-content'>")
        htmlBuilder.Append("				<p>Demise of relatives :</p>")
        htmlBuilder.Append("				<p>9:05 AM</p>")
        htmlBuilder.Append("			</div>")
        htmlBuilder.Append("		</div>")
        htmlBuilder.Append("	</section>")
        htmlBuilder.Append("</body>")
        htmlBuilder.Append("</html>")
        Return htmlBuilder.ToString()
    End Function
    Sub GetUserNameFromUPROF(ByRef UID As String)
        Dim connection As SqlConnection = New SqlConnection("data source=WIN-KSTUPT6CJRC;initial catalog=ASTROLOGYSOFTWARE_DB;integrated security=True;multipleactiveresultsets=True;")
        connection.Open()
        Dim cmd As New SqlCommand($"select USERNAME from UPROF WHERE USERID = '" + UID + "';", connection)
        Dim da As New SqlDataAdapter(cmd)
        Dim RowsData As New DataSet()
        da.Fill(RowsData)
        connection.Close()
        NameoftheChartOwner = RowsData.Tables(0).Rows(0)(0).Trim.ToString()
    End Sub
End Class
